rule PuTTY_install {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-07-01"
		versionApp = "Release 0.75"
		uuid = "7d655c5b-005a-4735-8c3f-fee4e20ea39f"
	strings: 
		$s0 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s1 = /putty\.exe\|a07396d107f47123nifest/
		$s2 = /simontatham\.puttypackageid/
		$s3 = /simontatham\.puttywindows\_win32/
		$s4 = /Zpackageidsimontatham\.puttya/
		$s5 = /Zwindows\_win32simontatham\.puttya/
		$s6 = /windows\_win32simontatham\.puttya/
		$s7 = /PUTTY\.EXE/
		$s8 = /PuTTY\-UsfH/
		$s9 = /PuTTY\-User\-Key\-FUser\-Key\-File\-2/
		$s10 = /puttygen\-pastekey/
		$s11 = /putty\-private\-key\-file\-mac\-key/
		$s12 = /PuTTY key format too new/
		$s13 = /puttygen\-savepriv/
		$s14 = /puttygen\-fingerprint/
		$s15 = /puttygen\-comment/
		$s16 = /puttygen\-conversions/
		$s17 = /PuTTYgen/
		$s18 = /PuTTYgen Error/
		$s19 = /PuTTYgen Fatal Error/
		$s20 = /puttygen\-save\-ppk\-version/
		$s21 = /pubkey\-puttygen/
		$s22 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s23 = /puttygen\-strength/
		$s24 = /Software\\SimonTatham\\PuTTY\\CHMPath/
		$s25 = /Software\\SimonTatham\\PuTTY64\\CHMPath/
		$s26 = /PuTTYgen Warning/
		$s27 = /puttygen\-save\-passphrase\-hashing/
		$s28 = /puttygen\-generate/
		$s29 = /puttygen\-passphrase/
		$s30 = /puttygen\-keytype/
		$s31 = /PuTTYgen Notice/
		$s32 = /puttygen\-load/
		$s33 = /puttygen\-savepub/
		$s34 = /Software\\SimonTatham\\PuTTY/
		$s35 = /\\PUTTY\.RND/
		$s36 = /PuTTY\-User\-Key\-File\-/
		$s37 = /PuTTY\-User\-Key\-File\-\%u\: \%s/
		$s38 = /   name\=\"PuTTYgen\"/
		$s39 = /putty\.install\.nuspecPK/
		$s40 = /tools\/putty\-64bit\-0\.75\-installer\.msiPK/
		$s41 = /tools\/putty\-arm64\-0\.75\-installer\.msiPK/
		$s42 = /PuTTY\-UsH/
		$s43 = /putty\.exH/
		$s44 = /PuTTY Key File Warning/
		$s45 = /Software\\SimonTatham\\PuTTY\\Sessions/
		$s46 = /\-restrict\_putty\_acl/
		$s47 = /\-restrict\-putty\-acl/
		$s48 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s49 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s50 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s51 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s52 = /Unable to execute PuTTY\!/
		$s53 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s54 = /PuTTYConfigBox/
		$s55 = /Local\\putty\-connshare\-mutex/
		$s56 = /putty \%s\&\%p\:\%u/
		$s57 = /PuTTY remote printer output/
		$s58 = /Software\\SimonTatham\\PuTTY\\Jumplist/
		$s59 = /Software\\SimonTatham\\PuTTY\\SshHostKeys/
		$s60 = /putty\%s\%s/
		$s61 = /putty \%s\@\%s/
		$s62 = /winadj\@putty\.projects\.tartarus\.org/
		$s63 = /simple\@putty\.projects\.tartarus\.org/
		$s64 = /putty\.log/
		$s65 = /\\\\\.\\pipe\\putty\-connshare/
		$s66 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
		$s67 = /Connect to PuTTY session \'/
		$s68 = /PuTTYgen\.exe/
		$s69 = /   name\=\"PuTTY\"/
		$s70 = /\[PuTTY README/
		$s71 = /putty\.install\.nuspec /
		$s72 = /PuTTY Installer/
		$s73 = /PuTTY release 0\.75 installer/
		$s74 = /\*\|PuTTYB\*\|/
		$s75 = /Eputty/
		$s76 = /O\*\|PuTTY/
		$s77 = /\(Gputty w/
		$s78 = /siteOPuTTY W/
		$s79 = /\@SimonTatham\.PuTTY/
		$s80 = /tools\/putty\-64bit\-/
		$s81 = /PuTTY\_File/
		$s82 = /PuTTYgen\_File/
		$s83 = /\/faq\-putty\-org\.html/
		$s84 = /\/faq\-puttyputty\.html/
		$s85 = /\/faq\-sillyputty\.html/
		$s86 = /\/pubkey\-puttygen\.html/
		$s87 = /\/puttygen\-comment\.html/
		$s88 = /\/puttygen\-conversions\.html/
		$s89 = /\/puttygen\-fingerprint\.html/
		$s90 = /\/puttygen\-generate\.html/
		$s91 = /\/puttygen\-generating\.html/
		$s92 = /\/puttygen\-keytype\.html/
		$s93 = /\/puttygen\-load\.html/
		$s94 = /\/puttygen\-passphrase\.html/
		$s95 = /\/puttygen\-pastekey\.html/
		$s96 = /\/puttygen\-primes\.html/
		$s97 = /\/puttygen\-save\-params\.html/
		$s98 = /\\\&\/puttygen\-save\-passphrase\-hashing\.html/
		$s99 = /\/puttygen\-save\-ppk\-version\.html/
		$s100 = /\/puttygen\-savepriv\.html/
		$s101 = /\/puttygen\-savepub\.html/
		$s102 = /\/puttygen\-strength\.html/
		$s103 = /PuTTY User Manual/
		$s104 = / PUTTY\(\~1/
		$s105 = /N  PUTTYM\~1\.LNK/
		$s106 = /N  PUTTYW\~1\.LNK/
		$s107 = /N  PuTTY\.lnk/
		$s108 = /N  PuTTYgen\.lnk/
		$s109 = /    \<id\>putty\.install\<\/id\>/
		$s110 = /PuTTY/
		$s111 = /putty\.exe/
		$s112 = /putty\-64bit\-0\.75\-installer\.msi/
		$s113 = /puttygen\.exe/
		$s114 = /putty\.chm/
		$s115 = /PuTTY Secure Copy client/
		$s116 = /r\\x69\\u007\(\[\(\[\(Kputty\"XOR\.Tem88\,73\,65\,92XOR/
		$s117 = /PuTTY64/
		$s118 = /C\:\\Program Files\\PuTTY\\/
		$s119 = /putty\~/
		$s120 = /puttygen\~/
		$s121 = /putty web site\~/
		$s122 = /putty manual\~/
	condition:
		97 of ($s*)
}