rule PuTTY_uninstall {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-07-01"
		versionApp = "Release 0.75"
		uuid = "ac4bc01f-717f-42c4-88fe-df4ee29e359a"
	strings: 
		$s0 = / PUTTY\(\~1/
		$s1 = /N  PUTTYM\~1\.LNK/
		$s2 = /N  PUTTYW\~1\.LNK/
		$s3 = /N  PuTTY\.lnk/
		$s4 = /N  PuTTYgen\.lnk/
		$s5 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s6 = /putty\.exe\|a07396d107f47123nifest/
		$s7 = /simontatham\.puttypackageid/
		$s8 = /simontatham\.puttywindows\_win32/
		$s9 = /Zpackageidsimontatham\.puttya/
		$s10 = /Zwindows\_win32simontatham\.puttya/
		$s11 = /windows\_win32simontatham\.puttya/
		$s12 = /PUTTY\.EXE/
		$s13 = /r\\x69\\u007\(\[\(\[\(Kputty\"XOR\.Tem88\,73\,65\,92XOR/
		$s14 = /PuTTY\-UsfH/
		$s15 = /PuTTY\-User\-Key\-FUser\-Key\-File\-2/
		$s16 = /puttygen\-pastekey/
		$s17 = /putty\-private\-key\-file\-mac\-key/
		$s18 = /PuTTY key format too new/
		$s19 = /puttygen\-savepriv/
		$s20 = /puttygen\-fingerprint/
		$s21 = /puttygen\-comment/
		$s22 = /puttygen\-conversions/
		$s23 = /PuTTYgen/
		$s24 = /PuTTYgen Error/
		$s25 = /PuTTYgen Fatal Error/
		$s26 = /puttygen\-save\-ppk\-version/
		$s27 = /pubkey\-puttygen/
		$s28 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s29 = /puttygen\-strength/
		$s30 = /Software\\SimonTatham\\PuTTY\\CHMPath/
		$s31 = /Software\\SimonTatham\\PuTTY64\\CHMPath/
		$s32 = /PuTTYgen Warning/
		$s33 = /puttygen\-save\-passphrase\-hashing/
		$s34 = /puttygen\-generate/
		$s35 = /puttygen\-passphrase/
		$s36 = /puttygen\-keytype/
		$s37 = /PuTTYgen Notice/
		$s38 = /puttygen\-load/
		$s39 = /puttygen\-savepub/
		$s40 = /Software\\SimonTatham\\PuTTY/
		$s41 = /\\PUTTY\.RND/
		$s42 = /PuTTY\-User\-Key\-File\-/
		$s43 = /PuTTY\-User\-Key\-File\-\%u\: \%s/
		$s44 = /   name\=\"PuTTYgen\"/
		$s45 = /PuTTY\-UsH/
		$s46 = /putty\.exH/
		$s47 = /PuTTY Key File Warning/
		$s48 = /Software\\SimonTatham\\PuTTY\\Sessions/
		$s49 = /\-restrict\_putty\_acl/
		$s50 = /\-restrict\-putty\-acl/
		$s51 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s52 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s53 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s54 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s55 = /Unable to execute PuTTY\!/
		$s56 = /PuTTY release 0\.75 \(64\-bit/
		$s57 = /putty\-64bit\-0\.75\-installer\.msi/
		$s58 = /PuTTY release 0\.75 \(64\-bit\)/
		$s59 = /PuTTY\_File/
		$s60 = /PuTTYgen\_File/
		$s61 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s62 = /PuTTYConfigBox/
		$s63 = /Local\\putty\-connshare\-mutex/
		$s64 = /putty \%s\&\%p\:\%u/
		$s65 = /PuTTY remote printer output/
		$s66 = /Software\\SimonTatham\\PuTTY\\Jumplist/
		$s67 = /Software\\SimonTatham\\PuTTY\\SshHostKeys/
		$s68 = /putty\%s\%s/
		$s69 = /putty \%s\@\%s/
		$s70 = /winadj\@putty\.projects\.tartarus\.org/
		$s71 = /simple\@putty\.projects\.tartarus\.org/
		$s72 = /putty\.log/
		$s73 = /\\\\\.\\pipe\\putty\-connshare/
		$s74 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
		$s75 = /Connect to PuTTY session \'/
		$s76 = /PuTTYgen\.exe/
		$s77 = /   name\=\"PuTTY\"/
		$s78 = /\[PuTTY README/
		$s79 = /PuTTY64/
		$s80 = /C\:\\Program Files\\PuTTY\\/
		$s81 = /putty\.install\.nuspecPK/
		$s82 = /tools\/putty\-64bit\-0\.75\-installer\.msiPK/
		$s83 = /tools\/putty\-arm64\-0\.75\-installer\.msiPK/
		$s84 = /putty\.install\.nuspec /
		$s85 = /\*\|PuTTYB\*\|/
		$s86 = /Eputty/
		$s87 = /O\*\|PuTTY/
		$s88 = /\(Gputty w/
		$s89 = /siteOPuTTY W/
		$s90 = /\@SimonTatham\.PuTTY/
		$s91 = /tools\/putty\-64bit\-/
		$s92 = /PuTTY Installer/
		$s93 = /PuTTY release 0\.75 installer/
		$s94 = /putty\~/
		$s95 = /puttygen\~/
		$s96 = /putty web site\~/
		$s97 = /putty manual\~/
		$s98 = /putty\.install v0\.75/
		$s99 = /    \<id\>putty\.install\<\/id\>/
		$s100 = /PuTTY/
		$s101 = /putty\.exe/
		$s102 = /puttygen\.exe/
		$s103 = /putty\.chm/
		$s104 = /PuTTY Secure Copy client/
	condition:
		83 of ($s*)
}