rule PuTTY_install {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-07-01"
		versionApp = "Release 0.75"
		uuid = "59aa696c-c484-44f5-ab1a-36c5840e0c90"
	strings: 
		$s0 = /putty\~/
		$s1 = /puttygen\~/
		$s2 = /putty web site\~/
		$s3 = /putty manual\~/
		$s4 = /PuTTY/
		$s5 = /putty\.exe/
		$s6 = /putty\.exe\|a07396d107f471234/
		$s7 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s8 = /PuTTY README/
		$s9 = /puttygen\.exe/
		$s10 = /simontatham\.puttypackageid/
		$s11 = /simontatham\.puttywindows\_win32/
		$s12 = /\|packageidsimontatham\.puttya/
		$s13 = /\|windows\_win32simontatham\.puttya/
		$s14 = /1Wwindows\_win32simontatham\.puttya/
		$s15 = /putty\.chm/
		$s16 = /putty\.msi/
		$s17 = /\*\|PuTTYB\*\|/
		$s18 = /Eputty/
		$s19 = /O\*\|PuTTY/
		$s20 = /\(Gputty w/
		$s21 = /siteOPuTTY W/
		$s22 = /\@SimonTatham\.PuTTY/
		$s23 = /PuTTY\-UsfH/
		$s24 = /PuTTY\-UsH/
		$s25 = /PuTTY\-User\-Key\-FUser\-Key\-File\-2/
		$s26 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s27 = /putty\-private\-key\-file\-mac\-key/
		$s28 = /Local\\putty\-connshare\-mutex/
		$s29 = /PuTTY key format too new/
		$s30 = /Software\\SimonTatham\\PuTTY\\SshHostKeys/
		$s31 = /Software\\SimonTatham\\PuTTY\\Sessions/
		$s32 = /winadj\@putty\.projects\.tartarus\.org/
		$s33 = /simple\@putty\.projects\.tartarus\.org/
		$s34 = /putty\.log/
		$s35 = /\\\\\.\\pipe\\putty\-connshare/
		$s36 = /Software\\SimonTatham\\PuTTY/
		$s37 = /\\PUTTY\.RND/
		$s38 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
		$s39 = /PuTTY\-User\-Key\-File\-/
		$s40 = /PuTTY Secure Copy client/
		$s41 = /r\\x69\\u007\(\[\(\[\(Kputty\"XOR\.Tem88\,73\,65\,92XOR/
		$s42 = /PuTTY64/
		$s43 = /C\:\\Program Files\\PuTTY\\/
		$s44 = /puttygen\-pastekey/
		$s45 = /puttygen\-savepriv/
		$s46 = /puttygen\-fingerprint/
		$s47 = /puttygen\-comment/
		$s48 = /puttygen\-conversions/
		$s49 = /PuTTYgen/
		$s50 = /PuTTYgen Error/
		$s51 = /PuTTYgen Fatal Error/
		$s52 = /puttygen\-save\-ppk\-version/
		$s53 = /pubkey\-puttygen/
		$s54 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s55 = /puttygen\-strength/
		$s56 = /Software\\SimonTatham\\PuTTY\\CHMPath/
		$s57 = /Software\\SimonTatham\\PuTTY64\\CHMPath/
		$s58 = /PuTTYgen Warning/
		$s59 = /puttygen\-save\-passphrase\-hashing/
		$s60 = /puttygen\-generate/
		$s61 = /puttygen\-passphrase/
		$s62 = /puttygen\-keytype/
		$s63 = /PuTTYgen Notice/
		$s64 = /puttygen\-load/
		$s65 = /puttygen\-savepub/
		$s66 = /PuTTY\-User\-Key\-File\-\%u\: \%s/
		$s67 = /   name\=\"PuTTYgen\"/
		$s68 = /PUTTY\.EXE/
		$s69 = /\/faq\-putty\-org\.html/
		$s70 = /\/faq\-puttyputty\.html/
		$s71 = /\/faq\-sillyputty\.html/
		$s72 = /\/pubkey\-puttygen\.html/
		$s73 = /\/puttygen\-comment\.html/
		$s74 = /\/puttygen\-conversions\.html/
		$s75 = /\/puttygen\-fingerprint\.html/
		$s76 = /\/puttygen\-generate\.html/
		$s77 = /\/puttygen\-generating\.html/
		$s78 = /\/puttygen\-keytype\.html/
		$s79 = /\/puttygen\-load\.html/
		$s80 = /\/puttygen\-passphrase\.html/
		$s81 = /\/puttygen\-pastekey\.html/
		$s82 = /\/puttygen\-primes\.html/
		$s83 = /\/puttygen\-save\-params\.html/
		$s84 = /\\\&\/puttygen\-save\-passphrase\-hashing\.html/
		$s85 = /\/puttygen\-save\-ppk\-version\.html/
		$s86 = /\/puttygen\-savepriv\.html/
		$s87 = /\/puttygen\-savepub\.html/
		$s88 = /\/puttygen\-strength\.html/
		$s89 = /PuTTY User Manual/
		$s90 = / PUTTY\(\~1/
		$s91 = /B  PUTTYM\~1\.LNK/
		$s92 = /B  PUTTYW\~1\.LNK/
		$s93 = /B  PuTTY\.lnk/
		$s94 = /B  PuTTYgen\.lnk/
		$s95 = /putty\.exH/
		$s96 = /PuTTY Key File Warning/
		$s97 = /\-restrict\_putty\_acl/
		$s98 = /\-restrict\-putty\-acl/
		$s99 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s100 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s101 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s102 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s103 = /Unable to execute PuTTY\!/
		$s104 = /PuTTY\_File/
		$s105 = /PuTTYgen\_File/
		$s106 = /PuTTY Installer/
		$s107 = /PuTTY release 0\.75 installer/
		$s108 = /PuTTYConfigBox/
		$s109 = /putty \%s\&\%p\:\%u/
		$s110 = /PuTTY remote printer output/
		$s111 = /Software\\SimonTatham\\PuTTY\\Jumplist/
		$s112 = /putty\%s\%s/
		$s113 = /putty \%s\@\%s/
		$s114 = /Connect to PuTTY session \'/
		$s115 = /PuTTYgen\.exe/
		$s116 = /   name\=\"PuTTY\"/
	condition:
		92 of ($s*)
}