rule putty_install {                                                                                                                                                                                                                [83/1928]
        meta:
                description = "Auto gene for putty"
                author = "David Cruciani"
                date = "2021-06-29"
                versionApp = "Release 0.75"
                uuid = "cd7960d2-b7a2-44bb-a607-10378e30dc33"
        strings:
                $s0 = /putty\.exe\|a07396d107f47123urce/
                $s1 = /puttygen\.exe\|a8e024fc7459f5f3/
                $s2 = /simontatham\.puttywindows\_win32\`/
                $s3 = /simontatham\.puttywindows\_win32\;/
                $s4 = /simontatham\.puttypackageid\`/
                $s5 = /Cpackageidsimontatham\.puttya/
                $s6 = /Cwindows\_win32simontatham\.puttya/
                $s7 = /\#windows\_win32simontatham\.puttya/
                $s8 = /Eputty/
                $s9 = /\(Gputty w/
                $s10 = /putty\~/
                $s11 = /puttygen\~/
                $s12 = /putty web site\~/
                $s13 = /putty manual\~/
                $s14 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
                $s15 = /putty\-private\-key\-file\-mac\-key/
                $s16 = /Local\\putty\-connshare\-mutex/
                $s17 = /putty \%s\&\%p\:\%u/
                $s18 = /putty\%s\%s/
                $s19 = /putty \%s\@\%s/
                $s20 = /\%s\\putty\_\%lu\_\%llu\.chm/
                $s21 = /winadj\@putty\.projects\.tartarus\.org/
                $s22 = /simple\@putty\.projects\.tartarus\.org/
                $s23 = /putty\.log/
                $s24 = /\\\\\.\\pipe\\putty\-connshare/
                $s25 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
                $s26 = /putty\.exe/
                $s27 = /puttygen\.exe/
                $s28 = /putty\.chm/
                $s29 = /putty\.msi/
                $s30 = /\/faq\-putty\-org\.html/
                $s31 = /\/faq\-puttyputty\.html/
                $s32 = /\/faq\-sillyputty\.html/
                $s33 = /\/pubkey\-puttygen\.html/
                $s34 = /\/puttygen\-comment\.html/
                $s35 = /\/puttygen\-conversions\.html/
                $s36 = /\/puttygen\-fingerprint\.html/
                $s37 = /\/puttygen\-generate\.html/
                $s38 = /\/puttygen\-generating\.html/
                $s39 = /\/puttygen\-keytype\.html/
                $s40 = /\/puttygen\-load\.html/
                $s41 = /\/puttygen\-passphrase\.html/
                $s42 = /\/puttygen\-pastekey\.html/
                $s43 = /\/puttygen\-primes\.html/
                $s44 = /\/puttygen\-save\-params\.html/
                $s45 = /\\\&\/puttygen\-save\-passphrase\-hashing\.html/
                $s46 = /\/puttygen\-save\-ppk\-version\.html/
                $s47 = /\/puttygen\-savepriv\.html/
                $s48 = /\/puttygen\-savepub\.html/
                $s49 = /\/puttygen\-strength\.html/
                $s50 = /puttygen\-pastekey/
                $s51 = /puttygen\-savepriv/
                $s52 = /puttygen\-fingerprint/
                $s53 = /puttygen\-comment/
		$s54 = /puttygen\-conversions/
                $s55 = /puttygen\-save\-ppk\-version/
                $s56 = /pubkey\-puttygen/
                $s57 = /puttygen\-strength/
                $s58 = /puttygen\-save\-passphrase\-hashing/
                $s59 = /puttygen\-generate/
                $s60 = /puttygen\-passphrase/
                $s61 = /puttygen\-keytype/
                $s62 = /puttygen\-load/
                $s63 = /puttygen\-savepub/
                $s64 = /putty\.exH/
                $s65 = /\-restrict\_putty\_acl/
                $s66 = /\-restrict\-putty\-acl/
                $s67 = /reencrypt\@putty\.projects\.tartarus\.org/
                $s68 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
                $s69 = /add\-ppk\@putty\.projects\.tartarus\.org/
                $s70 = /list\-extended\@putty\.projects\.tartarus\.org/
        condition:
                56 of ($s*)
}
