rule PuTTY_uninstall {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-06-30"
		versionApp = "Release 0.75"
		uuid = "c5c89fec-fe32-4c85-acd3-3c6915d630ca"
	strings: 
		$s0 = /putty\.exe\|a07396d107f47123urce/
		$s1 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s2 = /simontatham\.puttywindows\_win32\`/
		$s3 = /simontatham\.puttywindows\_win32\;/
		$s4 = /simontatham\.puttypackageid\`/
		$s5 = /Cpackageidsimontatham\.puttya/
		$s6 = /Cwindows\_win32simontatham\.puttya/
		$s7 = /\#windows\_win32simontatham\.puttya/
		$s8 = /C\:\\Program Files\\PuTTY\\/
		$s9 = /PuTTY release 0\.75 \(64\-bit\)/
		$s10 = /putty\.msi/
		$s11 = /PuTTYT\?elease 0\.75 \(64\-bit\)/
		$s12 = /\*\|PuTTYB\*\|/
		$s13 = /Eputty/
		$s14 = /O\*\|PuTTY/
		$s15 = /\(Gputty w/
		$s16 = /siteOPuTTY W/
		$s17 = /\@SimonTatham\.PuTTY/
		$s18 = /putty\~/
		$s19 = /puttygen\~/
		$s20 = /putty web site\~/
		$s21 = /putty manual\~/
		$s22 = /PuTTY64/
		$s23 = /PuTTY\-UsfH/
		$s24 = /PuTTY\-UsH/
		$s25 = /PuTTY\-User\-Key\-FUser\-Key\-File\-2/
		$s26 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s27 = /putty\-private\-key\-file\-mac\-key/
		$s28 = /PuTTYConfigBox/
		$s29 = /Local\\putty\-connshare\-mutex/
		$s30 = /PuTTY key format too new/
		$s31 = /putty \%s\&\%p\:\%u/
		$s32 = /PuTTY remote printer output/
		$s33 = /Software\\SimonTatham\\PuTTY\\Jumplist/
		$s34 = /Software\\SimonTatham\\PuTTY\\SshHostKeys/
		$s35 = /Software\\SimonTatham\\PuTTY\\Sessions/
		$s36 = /putty\%s\%s/
		$s37 = /putty \%s\@\%s/
		$s38 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s39 = /Software\\SimonTatham\\PuTTY\\CHMPath/
		$s40 = /Software\\SimonTatham\\PuTTY64\\CHMPath/
		$s41 = /winadj\@putty\.projects\.tartarus\.org/
		$s42 = /simple\@putty\.projects\.tartarus\.org/
		$s43 = /putty\.log/
		$s44 = /\\\\\.\\pipe\\putty\-connshare/
		$s45 = /Software\\SimonTatham\\PuTTY/
		$s46 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
		$s47 = /PuTTY\-User\-Key\-File\-/
		$s48 = /Connect to PuTTY session \'/
		$s49 = /PuTTYgen\.exe/
		$s50 = /   name\=\"PuTTY\"/
		$s51 = /PuTTY\_File/
		$s52 = /PuTTYgen\_File/
		$s53 = /PuTTY Installer/
		$s54 = /PuTTY release 0\.75 installer/
		$s55 = /Software\\SimonTatham\\PuTTY64\\PPKAssociation/
		$s56 = /Software\\SimonTatham\\PuTTY64\\PathEntry/
		$s57 = /Software\\SimonTatham\\PuTTY64\\StartMenu/
		$s58 = /23\\PuTTY \(64\-bit\)\\G/
		$s59 = /puttygen\.exe/
		$s60 = /putty\.chm/
		$s61 = /PuTTY README/
		$s62 = /PuTTY/
		$s63 = /D  PuTTY\.lnk/
		$s64 = /D  PuTTYgen\.lnk/
		$s65 = /PuTTY Secure Copy client/
		$s66 = /puttygen\-pastekey/
		$s67 = /puttygen\-savepriv/
		$s68 = /puttygen\-fingerprint/
		$s69 = /puttygen\-comment/
		$s70 = /puttygen\-conversions/
		$s71 = /PuTTYgen/
		$s72 = /PuTTYgen Error/
		$s73 = /PuTTYgen Fatal Error/
		$s74 = /puttygen\-save\-ppk\-version/
		$s75 = /pubkey\-puttygen/
		$s76 = /puttygen\-strength/
		$s77 = /PuTTYgen Warning/
		$s78 = /puttygen\-save\-passphrase\-hashing/
		$s79 = /puttygen\-generate/
		$s80 = /puttygen\-passphrase/
		$s81 = /puttygen\-keytype/
		$s82 = /PuTTYgen Notice/
		$s83 = /puttygen\-load/
		$s84 = /puttygen\-savepub/
		$s85 = /PuTTY\-User\-Key\-File\-\%u\: \%s/
		$s86 = /   name\=\"PuTTYgen\"/
		$s87 = /putty\.exH/
		$s88 = /PuTTY Key File Warning/
		$s89 = /\-restrict\_putty\_acl/
		$s90 = /\-restrict\-putty\-acl/
		$s91 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s92 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s93 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s94 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s95 = /Unable to execute PuTTY\!/
	condition:
		76 of ($s*)
}