rule PuTTY_install {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-06-30"
		versionApp = "Release 0.75"
		uuid = "3b3bb8da-f177-4a73-b517-4ca7799b2447"
	strings: 
		$s0 = /putty\.exe\|a07396d107f47123urce/
		$s1 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s2 = /simontatham\.puttywindows\_win32\`/
		$s3 = /simontatham\.puttywindows\_win32\;/
		$s4 = /simontatham\.puttypackageid\`/
		$s5 = /cpackageidsimontatham\.puttya/
		$s6 = /cwindows\_win32simontatham\.puttya/
		$s7 = /\#windows\_win32simontatham\.puttya/
		$s8 = /c\:\\program files\\putty\\/
		$s9 = /\*\|puttyb\*\|/
		$s10 = /eputty/
		$s11 = /o\*\|putty/
		$s12 = /\(gputty w/
		$s13 = /siteoputty w/
		$s14 = /\@simontatham\.putty/
		$s15 = /putty\~/
		$s16 = /puttygen\~/
		$s17 = /putty web site\~/
		$s18 = /putty manual\~/
		$s19 = /putty\-usfh/
		$s20 = /putty\-ush/
		$s21 = /putty\-user\-key\-fuser\-key\-file\-2/
		$s22 = /sshconnection\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s23 = /putty\-private\-key\-file\-mac\-key/
		$s24 = /puttyconfigbox/
		$s25 = /local\\putty\-connshare\-mutex/
		$s26 = /putty key format too new/
		$s27 = /putty \%s\&\%p\:\%u/
		$s28 = /putty remote printer output/
		$s29 = /software\\simontatham\\putty\\jumplist/
		$s30 = /software\\simontatham\\putty\\sshhostkeys/
		$s31 = /software\\simontatham\\putty\\sessions/
		$s32 = /putty\%s\%s/
		$s33 = /putty \%s\@\%s/
		$s34 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s35 = /software\\simontatham\\putty\\chmpath/
		$s36 = /software\\simontatham\\putty64\\chmpath/
		$s37 = /winadj\@putty\.projects\.tartarus\.org/
		$s38 = /simple\@putty\.projects\.tartarus\.org/
		$s39 = /putty\.log/
		$s40 = /\\\\\.\\pipe\\putty\-connshare/
		$s41 = /software\\simontatham\\putty/
		$s42 = /\\putty\.rnd/
		$s43 = /sshconnection\@putty\.projects\.tartarus\.org\-/
		$s44 = /putty\-user\-key\-file\-/
		$s45 = /connect to putty session \'/
		$s46 = /puttygen\.exe/
		$s47 = /   name\=\"putty\"/
		$s48 = /putty/
		$s49 = /putty\.exe/
		$s50 = /putty\_file/
		$s51 = /puttygen\_file/
		$s52 = /putty installer/
		$s53 = /putty release 0\.75 installer/
		$s54 = /putty readme/
		$s55 = /putty64/
		$s56 = /putty\.chm/
		$s57 = /putty\.msi/
		$s58 = /putty secure copy client/
		$s59 = /\/faq\-putty\-org\.html/
		$s60 = /\/faq\-puttyputty\.html/
		$s61 = /\/faq\-sillyputty\.html/
		$s62 = /\/pubkey\-puttygen\.html/
		$s63 = /\/puttygen\-comment\.html/
		$s64 = /\/puttygen\-conversions\.html/
		$s65 = /\/puttygen\-fingerprint\.html/
		$s66 = /\/puttygen\-generate\.html/
		$s67 = /\/puttygen\-generating\.html/
		$s68 = /\/puttygen\-keytype\.html/
		$s69 = /\/puttygen\-load\.html/
		$s70 = /\/puttygen\-passphrase\.html/
		$s71 = /\/puttygen\-pastekey\.html/
		$s72 = /\/puttygen\-primes\.html/
		$s73 = /\/puttygen\-save\-params\.html/
		$s74 = /\\\&\/puttygen\-save\-passphrase\-hashing\.html/
		$s75 = /\/puttygen\-save\-ppk\-version\.html/
		$s76 = /\/puttygen\-savepriv\.html/
		$s77 = /\/puttygen\-savepub\.html/
		$s78 = /\/puttygen\-strength\.html/
		$s79 = /putty user manual/
		$s80 = / putty\(\~1/
		$s81 = /d  puttym\~1\.lnk/
		$s82 = /d  puttyw\~1\.lnk/
		$s83 = /d  putty\.lnk/
		$s84 = /d  puttygen\.lnk/
		$s85 = /puttygen\-pastekey/
		$s86 = /puttygen\-savepriv/
		$s87 = /puttygen\-fingerprint/
		$s88 = /puttygen\-comment/
		$s89 = /puttygen\-conversions/
		$s90 = /puttygen/
		$s91 = /puttygen error/
		$s92 = /puttygen fatal error/
		$s93 = /puttygen\-save\-ppk\-version/
		$s94 = /pubkey\-puttygen/
		$s95 = /puttygen\-strength/
		$s96 = /puttygen warning/
		$s97 = /puttygen\-save\-passphrase\-hashing/
		$s98 = /puttygen\-generate/
		$s99 = /puttygen\-passphrase/
		$s100 = /puttygen\-keytype/
		$s101 = /puttygen notice/
		$s102 = /puttygen\-load/
		$s103 = /puttygen\-savepub/
		$s104 = /putty\-user\-key\-file\-\%u\: \%s/
		$s105 = /   name\=\"puttygen\"/
		$s106 = /putty\.exh/
		$s107 = /putty key file warning/
		$s108 = /\-restrict\_putty\_acl/
		$s109 = /\-restrict\-putty\-acl/
		$s110 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s111 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s112 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s113 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s114 = /unable to execute putty\!/
	condition:
		91 of ($s*)
}