rule PuTTY_uninstall {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-06-30"
		versionApp = "Release 0.75"
		uuid = "44c82bd4-f255-4f84-9141-48726ac128c3"
	strings: 
		$s0 = /putty\.exe\|a07396d107f47123urce/
		$s1 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s2 = /simontatham\.puttywindows\_win32\`/
		$s3 = /simontatham\.puttywindows\_win32\;/
		$s4 = /simontatham\.puttypackageid\`/
		$s5 = /cpackageidsimontatham\.puttya/
		$s6 = /cwindows\_win32simontatham\.puttya/
		$s7 = /\#windows\_win32simontatham\.puttya/
		$s8 = /c\:\\program files\\putty\\/
		$s9 = /putty release 0\.75 \(64\-bit\)/
		$s10 = /putty\.msi/
		$s11 = /puttyt\?elease 0\.75 \(64\-bit\)/
		$s12 = /\*\|puttyb\*\|/
		$s13 = /eputty/
		$s14 = /o\*\|putty/
		$s15 = /\(gputty w/
		$s16 = /siteoputty w/
		$s17 = /\@simontatham\.putty/
		$s18 = /putty\~/
		$s19 = /puttygen\~/
		$s20 = /putty web site\~/
		$s21 = /putty manual\~/
		$s22 = /putty\.exe/
		$s23 = /putty64/
		$s24 = /putty\-usfh/
		$s25 = /putty\-ush/
		$s26 = /putty\-user\-key\-fuser\-key\-file\-2/
		$s27 = /sshconnection\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s28 = /putty\-private\-key\-file\-mac\-key/
		$s29 = /puttyconfigbox/
		$s30 = /local\\putty\-connshare\-mutex/
		$s31 = /putty key format too new/
		$s32 = /putty \%s\&\%p\:\%u/
		$s33 = /putty remote printer output/
		$s34 = /software\\simontatham\\putty\\jumplist/
		$s35 = /software\\simontatham\\putty\\sshhostkeys/
		$s36 = /software\\simontatham\\putty\\sessions/
		$s37 = /putty\%s\%s/
		$s38 = /putty \%s\@\%s/
		$s39 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s40 = /software\\simontatham\\putty\\chmpath/
		$s41 = /software\\simontatham\\putty64\\chmpath/
		$s42 = /winadj\@putty\.projects\.tartarus\.org/
		$s43 = /simple\@putty\.projects\.tartarus\.org/
		$s44 = /putty\.log/
		$s45 = /\\\\\.\\pipe\\putty\-connshare/
		$s46 = /software\\simontatham\\putty/
		$s47 = /\\putty\.rnd/
		$s48 = /sshconnection\@putty\.projects\.tartarus\.org\-/
		$s49 = /putty\-user\-key\-file\-/
		$s50 = /connect to putty session \'/
		$s51 = /puttygen\.exe/
		$s52 = /   name\=\"putty\"/
		$s53 = /putty\_file/
		$s54 = /puttygen\_file/
		$s55 = /putty installer/
		$s56 = /putty release 0\.75 installer/
		$s57 = /software\\simontatham\\putty64\\ppkassociation/
		$s58 = /software\\simontatham\\putty64\\pathentry/
		$s59 = /software\\simontatham\\putty64\\startmenu/
		$s60 = /23\\putty \(64\-bit\)\\g/
		$s61 = /putty\.chm/
		$s62 = /putty readme/
		$s63 = /putty/
		$s64 = / putty\(\~1/
		$s65 = /d  puttym\~1\.lnk/
		$s66 = /d  puttyw\~1\.lnk/
		$s67 = /d  putty\.lnk/
		$s68 = /d  puttygen\.lnk/
		$s69 = /putty secure copy client/
		$s70 = /puttygen\-pastekey/
		$s71 = /puttygen\-savepriv/
		$s72 = /puttygen\-fingerprint/
		$s73 = /puttygen\-comment/
		$s74 = /puttygen\-conversions/
		$s75 = /puttygen/
		$s76 = /puttygen error/
		$s77 = /puttygen fatal error/
		$s78 = /puttygen\-save\-ppk\-version/
		$s79 = /pubkey\-puttygen/
		$s80 = /puttygen\-strength/
		$s81 = /puttygen warning/
		$s82 = /puttygen\-save\-passphrase\-hashing/
		$s83 = /puttygen\-generate/
		$s84 = /puttygen\-passphrase/
		$s85 = /puttygen\-keytype/
		$s86 = /puttygen notice/
		$s87 = /puttygen\-load/
		$s88 = /puttygen\-savepub/
		$s89 = /putty\-user\-key\-file\-\%u\: \%s/
		$s90 = /   name\=\"puttygen\"/
		$s91 = /putty\.exh/
		$s92 = /putty key file warning/
		$s93 = /\-restrict\_putty\_acl/
		$s94 = /\-restrict\-putty\-acl/
		$s95 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s96 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s97 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s98 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s99 = /unable to execute putty\!/
	condition:
		79 of ($s*)
}