rule putty_install {
	meta:
		description = "Auto gene for putty"
		author = "David Cruciani"
		date = "2021-06-11"
		versionApp = "Release 0.75"
		uuid = "6e233985-138e-47ad-9ea1-391948ad401e"
	strings: 
		$s0 = /Eputty/
		$s1 = /\(Gputty w/
		$s2 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s3 = /putty\-private\-key\-file\-mac\-key/
		$s4 = /Local\\putty\-connshare\-mutex/
		$s5 = /winadj\@putty\.projects\.tartarus\.org/
		$s6 = /simple\@putty\.projects\.tartarus\.org/
		$s7 = /putty\.log/
		$s8 = /\\\\\.\\pipe\\putty\-connshare/
		$s9 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
		$s10 = /putty\.exe/
		$s11 = /putty\~/
		$s12 = /puttygen\~/
		$s13 = /putty web site\~/
		$s14 = /putty manual\~/
		$s15 = /putty\.exe\|a07396d107f471232790d5/
		$s16 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s17 = /simontatham\.puttywindows\_win32/
		$s18 = /simontatham\.puttypackageid/
		$s19 = /packageidsimontatham\.putty\`/
		$s20 = /windows\_win32simontatham\.putty\`/
		$s21 = /putty\.msi/
		$s22 = /putty \%s\&\%p\:\%u/
		$s23 = /putty\%s\%s/
		$s24 = /putty \%s\@\%s/
		$s25 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s26 = /puttygen\-pastekey/
		$s27 = /puttygen\-savepriv/
		$s28 = /puttygen\-fingerprint/
		$s29 = /puttygen\-comment/
		$s30 = /puttygen\-conversions/
		$s31 = /puttygen\-save\-ppk\-version/
		$s32 = /pubkey\-puttygen/
		$s33 = /puttygen\-strength/
		$s34 = /puttygen\-save\-passphrase\-hashing/
		$s35 = /puttygen\-generate/
		$s36 = /puttygen\-passphrase/
		$s37 = /puttygen\-keytype/
		$s38 = /puttygen\-load/
		$s39 = /puttygen\-savepub/
		$s40 = /putty\.exH/
		$s41 = /\-restrict\_putty\_acl/
		$s42 = /\-restrict\-putty\-acl/
		$s43 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s44 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s45 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s46 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s47 = /puttygen\.exe/
		$s48 = /putty\.chm/
		$s49 = /putty\.install v0\.75/
		$s50 = /  \'putty\'\: COLORS\_16\,/
		$s51 = /putty/
		$s52 = /TERM putty/
		$s53 = /\/faq\-putty\-org\.html/
		$s54 = /\/faq\-puttyputty\.html/
		$s55 = /\/faq\-sillyputty\.html/
		$s56 = /\/pubkey\-puttygen\.html/
		$s57 = /\/puttygen\-comment\.html/
		$s58 = /\/puttygen\-conversions\.html/
		$s59 = /\/puttygen\-fingerprint\.html/
		$s60 = /\/puttygen\-generate\.html/
		$s61 = /\/puttygen\-generating\.html/
		$s62 = /\/puttygen\-keytype\.html/
		$s63 = /\/puttygen\-load\.html/
		$s64 = /\/puttygen\-passphrase\.html/
		$s65 = /\/puttygen\-pastekey\.html/
		$s66 = /\/puttygen\-primes\.html/
		$s67 = /\/puttygen\-save\-params\.html/
		$s68 = /\\\&\/puttygen\-save\-passphrase\-hashing\.html/
		$s69 = /\/puttygen\-save\-ppk\-version\.html/
		$s70 = /\/puttygen\-savepriv\.html/
		$s71 = /\/puttygen\-savepub\.html/
		$s72 = /\/puttygen\-strength\.html/
	condition:
		57 of ($s*)
}