rule PuTTY_install {
	meta:
		description = "Auto gene for PuTTY"
		author = "David Cruciani"
		date = "2021-06-30"
		versionApp = "Release 0.75"
		uuid = "76cbe830-6ba7-4f85-9e65-b0ae45284f5f"
	strings: 
		$s0 = /putty\.exe\|a07396d107f47123urce/
		$s1 = /puttygen\.exe\|a8e024fc7459f5f3/
		$s2 = /simontatham\.puttywindows\_win32\`/
		$s3 = /simontatham\.puttywindows\_win32\;/
		$s4 = /simontatham\.puttypackageid\`/
		$s5 = /Cpackageidsimontatham\.puttya/
		$s6 = /Cwindows\_win32simontatham\.puttya/
		$s7 = /\#windows\_win32simontatham\.puttya/
		$s8 = /C\:\\Program Files\\PuTTY\\/
		$s9 = /\*\|PuTTYB\*\|/
		$s10 = /Eputty/
		$s11 = /O\*\|PuTTY/
		$s12 = /\(Gputty w/
		$s13 = /siteOPuTTY W/
		$s14 = /\@SimonTatham\.PuTTY/
		$s15 = /putty\~/
		$s16 = /puttygen\~/
		$s17 = /putty web site\~/
		$s18 = /putty manual\~/
		$s19 = /PuTTY\-UsfH/
		$s20 = /PuTTY\-UsH/
		$s21 = /PuTTY\-User\-Key\-FUser\-Key\-File\-2/
		$s22 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-2\.0\-/
		$s23 = /putty\-private\-key\-file\-mac\-key/
		$s24 = /PuTTYConfigBox/
		$s25 = /Local\\putty\-connshare\-mutex/
		$s26 = /PuTTY key format too new/
		$s27 = /putty \%s\&\%p\:\%u/
		$s28 = /PuTTY remote printer output/
		$s29 = /Software\\SimonTatham\\PuTTY\\Jumplist/
		$s30 = /Software\\SimonTatham\\PuTTY\\SshHostKeys/
		$s31 = /Software\\SimonTatham\\PuTTY\\Sessions/
		$s32 = /putty\%s\%s/
		$s33 = /putty \%s\@\%s/
		$s34 = /\%s\\putty\_\%lu\_\%llu\.chm/
		$s35 = /Software\\SimonTatham\\PuTTY\\CHMPath/
		$s36 = /Software\\SimonTatham\\PuTTY64\\CHMPath/
		$s37 = /winadj\@putty\.projects\.tartarus\.org/
		$s38 = /simple\@putty\.projects\.tartarus\.org/
		$s39 = /putty\.log/
		$s40 = /\\\\\.\\pipe\\putty\-connshare/
		$s41 = /Software\\SimonTatham\\PuTTY/
		$s42 = /SSHCONNECTION\@putty\.projects\.tartarus\.org\-/
		$s43 = /PuTTY\-User\-Key\-File\-/
		$s44 = /Connect to PuTTY session \'/
		$s45 = /PuTTYgen\.exe/
		$s46 = /   name\=\"PuTTY\"/
		$s47 = /PuTTY/
		$s48 = /putty\.exe/
		$s49 = /PuTTY\_File/
		$s50 = /PuTTYgen\_File/
		$s51 = /PuTTY Installer/
		$s52 = /PuTTY release 0\.75 installer/
		$s53 = /PuTTY README/
		$s54 = /PuTTY64/
		$s55 = /puttygen\.exe/
		$s56 = /putty\.chm/
		$s57 = /putty\.msi/
		$s58 = /PuTTY Secure Copy client/
		$s59 = /\/faq\-putty\-org\.html/
		$s60 = /\/faq\-puttyputty\.html/
		$s61 = /\/faq\-sillyputty\.html/
		$s62 = /\/pubkey\-puttygen\.html/
		$s63 = /\/puttygen\-comment\.html/
		$s64 = /\/puttygen\-conversions\.html/
		$s65 = /\/puttygen\-fingerprint\.html/
		$s66 = /\/puttygen\-generate\.html/
		$s67 = /\/puttygen\-generating\.html/
		$s68 = /\/puttygen\-keytype\.html/
		$s69 = /\/puttygen\-load\.html/
		$s70 = /\/puttygen\-passphrase\.html/
		$s71 = /\/puttygen\-pastekey\.html/
		$s72 = /\/puttygen\-primes\.html/
		$s73 = /\/puttygen\-save\-params\.html/
		$s74 = /\\\&\/puttygen\-save\-passphrase\-hashing\.html/
		$s75 = /\/puttygen\-save\-ppk\-version\.html/
		$s76 = /\/puttygen\-savepriv\.html/
		$s77 = /\/puttygen\-savepub\.html/
		$s78 = /\/puttygen\-strength\.html/
		$s79 = /PuTTY User Manual/
		$s80 = /D  PuTTY\.lnk/
		$s81 = /D  PuTTYgen\.lnk/
		$s82 = /puttygen\-pastekey/
		$s83 = /puttygen\-savepriv/
		$s84 = /puttygen\-fingerprint/
		$s85 = /puttygen\-comment/
		$s86 = /puttygen\-conversions/
		$s87 = /PuTTYgen/
		$s88 = /PuTTYgen Error/
		$s89 = /PuTTYgen Fatal Error/
		$s90 = /puttygen\-save\-ppk\-version/
		$s91 = /pubkey\-puttygen/
		$s92 = /puttygen\-strength/
		$s93 = /PuTTYgen Warning/
		$s94 = /puttygen\-save\-passphrase\-hashing/
		$s95 = /puttygen\-generate/
		$s96 = /puttygen\-passphrase/
		$s97 = /puttygen\-keytype/
		$s98 = /PuTTYgen Notice/
		$s99 = /puttygen\-load/
		$s100 = /puttygen\-savepub/
		$s101 = /PuTTY\-User\-Key\-File\-\%u\: \%s/
		$s102 = /   name\=\"PuTTYgen\"/
		$s103 = /putty\.exH/
		$s104 = /PuTTY Key File Warning/
		$s105 = /\-restrict\_putty\_acl/
		$s106 = /\-restrict\-putty\-acl/
		$s107 = /reencrypt\@putty\.projects\.tartarus\.org/
		$s108 = /reencrypt\-all\@putty\.projects\.tartarus\.org/
		$s109 = /add\-ppk\@putty\.projects\.tartarus\.org/
		$s110 = /list\-extended\@putty\.projects\.tartarus\.org/
		$s111 = /Unable to execute PuTTY\!/
	condition:
		88 of ($s*)
}