rule vlc_uninstall {
	meta:
		description = "Auto gene for vlc"
		author = "David Cruciani"
		date = "2021-06-07"
		versionApp = "3,0,14,0"
		uuid = "347bcb6d-a6c4-4340-a36b-6f300b4e3ec9"
	strings: 
		$s0 = /vlc\_entry\_\_3\_0\_0f/
		$s1 = /vlc\_entry\_copyright\_\_3\_0\_0f/
		$s2 = /vlc\_entry\_license\_\_3\_0\_0f/
		$s3 = /vlc\_Log/
		$s4 = /vlc\_fopen/
		$s5 = /libvlccore\.dll/
		$s6 = /pnlvlcont/
		$s7 = /8vlc/
		$s8 = /xvlc/
		$s9 = /cavlc\:\%d /
		$s10 = /vlc\_object\_create/
		$s11 = /vlc\_object\_release/
		$s12 = /vlc\_ureduce/
		$s13 = /vlc\_fourcc\_GetChromaDescription/
		$s14 = /vlc\_CPU/
		$s15 = /vlc\_mutex\_destroy/
		$s16 = /vlc\_mutex\_init/
		$s17 = /vlc\_mutex\_lock/
		$s18 = /vlc\_mutex\_unlock/
		$s19 = /vlc\_path2uri/
		$s20 = /vlc\_fourcc\_IsYUV/
		$s21 = /cache vlc 3\.0\.14\"/
		$s22 = /vlc\_gettext/
		$s23 = /vlc\_mrand48/
		$s24 = /vlc\.exe/
		$s25 = /vlc\_rename/
		$s26 = /vlc\_strerror\_c/
		$s27 = /vlc\_unlink/
		$s28 = /vlc\_cancel/
		$s29 = /vlc\_clone/
		$s30 = /vlc\_join/
		$s31 = /vlc\_restorecancel/
		$s32 = /vlc\_savecancel/
		$s33 = /vlc\_cond\_destroy/
		$s34 = /vlc\_cond\_init/
		$s35 = /vlc\_cond\_signal/
		$s36 = /vlc\_cond\_wait/
		$s37 = /vlc\_fourcc\_AreUVPlanesSwapped/
		$s38 = /vlc\_fourcc\_GetRGBFallback/
		$s39 = /vlc\_fourcc\_GetYUVFallback/
		$s40 = /vlc\_gl\_Create/
		$s41 = /vlc\_gl\_Hold/
		$s42 = /vlc\_gl\_Release/
		$s43 = /vlc\_memstream\_close/
		$s44 = /vlc\_memstream\_open/
		$s45 = /vlc\_memstream\_printf/
		$s46 = /vlc\_memstream\_puts/
		$s47 = /vlc\_memstream\_write/
		$s48 = /vlc\_fourcc\_GetCodecFromString/
		$s49 = /vlc\_control\_cancel/
		$s50 = /vlc\_obj\_malloc/
		$s51 = /vlc\_sem\_destroy/
		$s52 = /vlc\_sem\_init/
		$s53 = /vlc\_sem\_post/
		$s54 = /vlc\_sem\_wait/
		$s55 = /vlc\_gl\_surface\_CheckSize/
		$s56 = /vlc\_gl\_surface\_Create/
		$s57 = /vlc\_gl\_surface\_Destroy/
		$s58 = /Cvlc\(aa/
		$s59 = /VCvlc fmedia /
		$s60 = /hc\-vlc\.nl/
		$s61 = /D\$ Hvlc/
		$s62 = /\?cFBvlc\.I/
		$s63 = /vlc6zqf/
		$s64 = /\*\|vlc media player\*\|vlx6717/
		$s65 = /\*\|vlc media player\*\|vlv6720/
		$s66 = /\*\|vlc media player\*\|vls7366/
		$s67 = /\*\|vlc media player\*\|vcl7100/
		$s68 = /\*\|\*\|vlc5573/
		$s69 = /9vlcb/
		$s70 = /vlc0\%I/
		$s71 = /MementoSection\_SEC\_EXT\_Other\_\.vlc/
		$s72 = /vlc\_getaddrinfo/
		$s73 = /vlc\_interrupt\_register/
		$s74 = /vlc\_interrupt\_unregister/
		$s75 = /vlc\_killed/
		$s76 = /vlc\_obj\_calloc/
		$s77 = /vlc\_obj\_free/
		$s78 = /vlc\_keystore\_release\_entries/
		$s79 = /vlc\_fourcc\_GetCodecAudio/
		$s80 = /vlco/
		$s81 = /\~fcvlchA\{DK/
		$s82 = /\<vlc\</
		$s83 = /vlc\_/
		$s84 = /Pvlc\)/
		$s85 = /Qvlc/
		$s86 = /6vlcA/
		$s87 = /vlc\/Y/
		$s88 = /vlcS/
		$s89 = /Avlc\-o/
		$s90 = /libvlc/
		$s91 = /\(\(vlc /
		$s92 = /Nvlc/
		$s93 = /\{\\\*\\pn\\pnlvlcont\\pnf2\\pnindent360\{\\pntxtb\\\'b7\}\}/
		$s94 = /8 matchFileMQ1P\$npvlc\\\.dll/
		$s95 = /0d1ogpddzvlcrnd2vxtfr7ucnvyt/
		$s96 = /4ZMBBKlWyhpdsKqKnbXEkuo4CnSxw6b7svlcKIJWfEA\=\.pem/
		$s97 = /spellingv\;lcvlc10098/
		$s98 = /spellingvl\;cvlc10174/
		$s99 = /spellingv lcvlc10220/
		$s100 = /spellingvllcvlc10469/
		$s101 = /spellingvlclvlc 10480/
		$s102 = /spellingvlcxvlc 10716/
		$s103 = /spellingvvlcvlc10786/
		$s104 = /spellingvlccvlc 11062/
		$s105 = /spellingvlcvlc 21839/
		$s106 = /libvlc\_Quit/
		$s107 = /vvlc\_\_lmhhl/
		$s108 = /9\?vlcXl/
		$s109 = /2\+\+vlc\\\\\"\}v\"/
		$s110 = /vlc\_close/
		$s111 = /vlc\_global\_mutex/
		$s112 = /vlc\_open/
		$s113 = /vlc\_rand\_bytes/
		$s114 = /vlc\_strftime/
		$s115 = /vlc\_write/
		$s116 = /vlc\_testcancel/
		$s117 = /http\:\/\/www\.videolan\.org\/vlc/
		$s118 = /vlc\_UrlClean/
		$s119 = /vlc\_UrlParse/
		$s120 = /vlc\_getnameinfo/
		$s121 = /Mtvlc\<\}/
		$s122 = /\]Cvlc\:EA\./
		$s123 = / cK0vlc/
		$s124 = /n\{vlc/
		$s125 = /\@4ZMBBKlWyhpdsKqKnbXEkuo4CnSxw6b7svlcKIJWfEA\=\.pem/
		$s126 = /vlc\-q/
		$s127 = /ZTvlc/
		$s128 = /zvlc/
		$s129 = /\)vlc/
		$s130 = /vlct\`\$a\`\,e\%/
		$s131 = /vlcN/
		$s132 = /vlcAK/
		$s133 = /vlcT\+/
		$s134 = /vlcX/
		$s135 = /vlc2\./
		$s136 = /vlc\_timer\_create/
		$s137 = /vlc\_timer\_destroy/
		$s138 = /vlc\_timer\_schedule/
		$s139 = /vlc\_tls\_Read/
		$s140 = /vlc\_tls\_SessionDelete/
		$s141 = /vlc\_tls\_SocketOpenTCP/
		$s142 = /\?vlc/
		$s143 = /vlc\_UrlParseFixup/
		$s144 = /vlc\_credential\_clean/
		$s145 = /vlc\_credential\_get/
		$s146 = /vlc\_credential\_init/
		$s147 = /vlc\_credential\_store/
		$s148 = /vlc\_readdir\_helper\_additem/
		$s149 = /vlc\_readdir\_helper\_finish/
		$s150 = /vlc\_readdir\_helper\_init/
		$s151 = /vlc\_uri\_decode\_duplicate/
		$s152 = /vlc\_poll\_i11e/
		$s153 = /kfvlc/
		$s154 = /cvlc/
		$s155 = /7vlc/
		$s156 = /vlc\_MMNotificationClient\_OnDeviceStateChanged/
		$s157 = /vlc\_MMNotificationClient\_OnDeviceAdded/
		$s158 = /vlc\_MMNotificationClient\_OnDeviceRemoved/
		$s159 = /vlc\_MMNotificationClient\_OnDefaultDeviceChange/
		$s160 = /vlc\_MMNotificationClient\_OnPropertyValueChanged/
		$s161 = /vlc\_AudioSessionEvents\_OnDisplayNameChanged/
		$s162 = /vlc\_AudioSessionEvents\_OnIconPathChanged/
		$s163 = /vlc\_AudioSessionEvents\_OnSimpleVolumeChanged/
		$s164 = /vlc\_AudioSessionEvents\_OnChannelVolumeChanged/
		$s165 = /vlc\_AudioSessionEvents\_OnGroupingParamChanged/
		$s166 = /vlc\_AudioSessionEvents\_OnStateChanged/
		$s167 = /vlc\_AudioSessionEvents\_OnSessionDisconnected/
		$s168 = /vlc\_module\_load/
		$s169 = /vlc\_module\_unload/
		$s170 = /vlc\.nuspec /
		$s171 = /vlc\_dialog\_wait\_question/
		$s172 = /vlc\_dup/
		$s173 = /\;vlc/
		$s174 = /evlcn/
		$s175 = /vlcy/
		$s176 = /vlcE\&vh/
		$s177 = /vlc\_http\_HostNew/
		$s178 = /vlc\_https\_HostNew/
		$s179 = /vlc\_cond\_broadcast/
		$s180 = /\<\?vlc \-\-\[\[/
		$s181 = /vlcgv\/A/
		$s182 = /vlc\_fifo\_DequeueUnlocked/
		$s183 = /vlc\_fifo\_GetCount/
		$s184 = /vlc\_fifo\_Lock/
		$s185 = /vlc\_fifo\_Signal/
		$s186 = /vlc\_fifo\_Unlock/
		$s187 = /vlc\_fifo\_Wait/
		$s188 = /vlc\_mwait\_i11e/
		$s189 = /vlc\_recvfrom\_i11e/
		$s190 = /vlc\_uri\_compose/
		$s191 = /4Rvlc/
		$s192 = /vlc\]/
		$s193 = /vvlc/
		$s194 = /Ovlc/
		$s195 = /vlcM/
		$s196 = /X\%vlc/
		$s197 = /Hvlc/
		$s198 = / vlc /
		$s199 = / \'cvlc\' /
		$s200 = /32 ac vlc/
		$s201 = / \"ac vlc\" /
		$s202 = /  vlc\:\/\//
		$s203 = /vlc\-snap/
		$s204 = / vlc/
		$s205 = / vlc\-help\.txt /
		$s206 = /18vlc\_player\_options/
		$s207 = /FvP14libvlc\_media\_tE/
		$s208 = /FvP17libvlc\_instance\_tE/
		$s209 = /FvP19libvlc\_media\_list\_tE/
		$s210 = /FvP21libvlc\_media\_player\_tE/
		$s211 = /FvP22libvlc\_event\_manager\_tE/
		$s212 = /FvP26libvlc\_media\_list\_player\_tE/
		$s213 = /PFvP14libvlc\_media\_tE/
		$s214 = /PFvP17libvlc\_instance\_tE/
		$s215 = /PFvP19libvlc\_media\_list\_tE/
		$s216 = /PFvP21libvlc\_media\_player\_tE/
		$s217 = /PFvP22libvlc\_event\_manager\_tE/
		$s218 = /PFvP26libvlc\_media\_list\_player\_tE/
		$s219 = /axvlc\.dll/
		$s220 = /libvlc\_audio\_get\_channel/
		$s221 = /libvlc\_audio\_get\_mute/
		$s222 = /libvlc\_audio\_get\_track/
		$s223 = /libvlc\_audio\_get\_track\_count/
		$s224 = /libvlc\_audio\_get\_track\_description/
		$s225 = /libvlc\_audio\_get\_volume/
		$s226 = /libvlc\_audio\_set\_channel/
		$s227 = /libvlc\_audio\_set\_mute/
		$s228 = /libvlc\_audio\_set\_track/
		$s229 = /libvlc\_audio\_set\_volume/
		$s230 = /libvlc\_audio\_toggle\_mute/
		$s231 = /libvlc\_chapter\_descriptions\_release/
		$s232 = /libvlc\_event\_attach/
		$s233 = /libvlc\_event\_detach/
		$s234 = /libvlc\_free/
		$s235 = /libvlc\_get\_version/
		$s236 = /libvlc\_media\_add\_option\_flag/
		$s237 = /libvlc\_media\_event\_manager/
		$s238 = /libvlc\_media\_get\_duration/
		$s239 = /libvlc\_media\_get\_meta/
		$s240 = /libvlc\_media\_list\_add\_media/
		$s241 = /libvlc\_media\_list\_count/
		$s242 = /libvlc\_media\_list\_index\_of\_item/
		$s243 = /libvlc\_media\_list\_item\_at\_index/
		$s244 = /libvlc\_media\_list\_lock/
		$s245 = /libvlc\_media\_list\_new/
		$s246 = /libvlc\_media\_list\_player\_is\_playing/
		$s247 = /libvlc\_media\_list\_player\_new/
		$s248 = /libvlc\_media\_list\_player\_next/
		$s249 = /libvlc\_media\_list\_player\_pause/
		$s250 = /libvlc\_media\_list\_player\_play/
		$s251 = /libvlc\_media\_list\_player\_play\_item\_at\_index/
		$s252 = /libvlc\_media\_list\_player\_previous/
		$s253 = /libvlc\_media\_list\_player\_release/
		$s254 = /libvlc\_media\_list\_player\_set\_media\_list/
		$s255 = /libvlc\_media\_list\_player\_set\_media\_player/
		$s256 = /libvlc\_media\_list\_player\_set\_playback\_mode/
		$s257 = /libvlc\_media\_list\_player\_stop/
		$s258 = /libvlc\_media\_list\_release/
		$s259 = /libvlc\_media\_list\_remove\_index/
		$s260 = /libvlc\_media\_list\_unlock/
		$s261 = /libvlc\_media\_new\_location/
		$s262 = /libvlc\_media\_parse\_with\_options/
		$s263 = /libvlc\_media\_player\_event\_manager/
		$s264 = /libvlc\_media\_player\_get\_chapter/
		$s265 = /libvlc\_media\_player\_get\_chapter\_count/
		$s266 = /libvlc\_media\_player\_get\_chapter\_count\_for\_title/
		$s267 = /libvlc\_media\_player\_get\_full\_chapter\_descriptions/
		$s268 = /libvlc\_media\_player\_get\_full\_title\_descriptions/
		$s269 = /libvlc\_media\_player\_get\_length/
		$s270 = /libvlc\_media\_player\_get\_media/
		$s271 = /libvlc\_media\_player\_get\_position/
		$s272 = /libvlc\_media\_player\_get\_rate/
		$s273 = /libvlc\_media\_player\_get\_state/
		$s274 = /libvlc\_media\_player\_get\_time/
		$s275 = /libvlc\_media\_player\_get\_title/
		$s276 = /libvlc\_media\_player\_get\_title\_count/
		$s277 = /libvlc\_media\_player\_has\_vout/
		$s278 = /libvlc\_media\_player\_new/
		$s279 = /libvlc\_media\_player\_next\_chapter/
		$s280 = /libvlc\_media\_player\_previous\_chapter/
		$s281 = /libvlc\_media\_player\_release/
		$s282 = /libvlc\_media\_player\_set\_chapter/
		$s283 = /libvlc\_media\_player\_set\_hwnd/
		$s284 = /libvlc\_media\_player\_set\_pause/
		$s285 = /libvlc\_media\_player\_set\_position/
		$s286 = /libvlc\_media\_player\_set\_rate/
		$s287 = /libvlc\_media\_player\_set\_time/
		$s288 = /libvlc\_media\_player\_set\_title/
		$s289 = /libvlc\_media\_release/
		$s290 = /libvlc\_media\_retain/
		$s291 = /libvlc\_media\_tracks\_get/
		$s292 = /libvlc\_media\_tracks\_release/
		$s293 = /libvlc\_new/
		$s294 = /libvlc\_release/
		$s295 = /libvlc\_title\_descriptions\_release/
		$s296 = /libvlc\_track\_description\_list\_release/
		$s297 = /libvlc\_video\_get\_aspect\_ratio/
		$s298 = /libvlc\_video\_get\_crop\_geometry/
		$s299 = /libvlc\_video\_get\_logo\_int/
		$s300 = /libvlc\_video\_get\_marquee\_int/
		$s301 = /libvlc\_video\_get\_marquee\_string/
		$s302 = /libvlc\_video\_get\_scale/
		$s303 = /libvlc\_video\_get\_size/
		$s304 = /libvlc\_video\_get\_spu/
		$s305 = /libvlc\_video\_get\_spu\_count/
		$s306 = /libvlc\_video\_get\_spu\_description/
		$s307 = /libvlc\_video\_get\_teletext/
		$s308 = /libvlc\_video\_get\_track/
		$s309 = /libvlc\_video\_get\_track\_count/
		$s310 = /libvlc\_video\_get\_track\_description/
		$s311 = /libvlc\_video\_set\_aspect\_ratio/
		$s312 = /libvlc\_video\_set\_crop\_geometry/
		$s313 = /libvlc\_video\_set\_deinterlace/
		$s314 = /libvlc\_video\_set\_logo\_int/
		$s315 = /libvlc\_video\_set\_logo\_string/
		$s316 = /libvlc\_video\_set\_marquee\_int/
		$s317 = /libvlc\_video\_set\_marquee\_string/
		$s318 = /libvlc\_video\_set\_scale/
		$s319 = /libvlc\_video\_set\_spu/
		$s320 = /libvlc\_video\_set\_teletext/
		$s321 = /libvlc\_video\_set\_track/
		$s322 = /libvlc\_video\_take\_snapshot/
		$s323 = /libvlc\.dll/
		$s324 = /name\=\"axvlc\.dll\"/
		$s325 = /vlc\</
		$s326 = /Dvlcal/
		$s327 = /\#vlcg/
		$s328 = /\`vlc\$p\{/
		$s329 = /vlc\~/
		$s330 = /vlcq/
		$s331 = /vlc\-/
		$s332 = /vlc\-help\.txt /
		$s333 = / \"vlc \-I qt\" /
		$s334 = /\. vlc /
		$s335 = /\, \"ac vlc\" /
		$s336 = /vlc\:\/\/pause\:\<seconds\>  /
		$s337 = /vlc\:\/\/quit  VLC/
		$s338 = /1vlc/
		$s339 = /equalizer\-vlcfreqs/
		$s340 = /\]vlc/
		$s341 = /vlc\_openat/
		$s342 = /vlc\_opendir/
		$s343 = /vlc\_read\_i11e/
		$s344 = /vlc\_readdir/
		$s345 = /vlc\_stat/
		$s346 = /vlc\_uri\_encode/
		$s347 = /\<\?vlc/
		$s348 = /\<\?vlc/
		$s349 = /\<\?vlc/
		$s350 = /vlc media player\~/
		$s351 = /vlc media player skinned\~/
		$s352 = /vlc\-log\.html/
		$s353 = /vlc\-log\.txt/
		$s354 = /vlc v3\.0\.14/
		$s355 = /vlc v3\.0\.14 \[Approved\]/
		$s356 = /Ivlc/
		$s357 = /vvlcT/
		$s358 = /qvlc/
		$s359 = /vlc\-cache\-gen\.exe/
		$s360 = /npvlc\.dll/
		$s361 = /locale\\ach\\LC\_MESSAGES\\vlc\.mo/
		$s362 = /locale\\af\\LC\_MESSAGES\\vlc\.mo/
		$s363 = /locale\\am\\LC\_MESSAGES\\vlc\.mo/
		$s364 = /locale\\am\_ET\\LC\_MESSAGES\\vlc\.mo/
		$s365 = /locale\\an\\LC\_MESSAGES\\vlc\.mo/
		$s366 = /locale\\ar\\LC\_MESSAGES\\vlc\.mo/
		$s367 = /locale\\ast\\LC\_MESSAGES\\vlc\.mo/
		$s368 = /locale\\as\_IN\\LC\_MESSAGES\\vlc\.mo/
		$s369 = /locale\\be\\LC\_MESSAGES\\vlc\.mo/
		$s370 = /locale\\bg\\LC\_MESSAGES\\vlc\.mo/
		$s371 = /locale\\bn\\LC\_MESSAGES\\vlc\.mo/
		$s372 = /locale\\bn\_IN\\LC\_MESSAGES\\vlc\.mo/
		$s373 = /locale\\br\\LC\_MESSAGES\\vlc\.mo/
		$s374 = /locale\\brx\\LC\_MESSAGES\\vlc\.mo/
		$s375 = /locale\\bs\\LC\_MESSAGES\\vlc\.mo/
		$s376 = /locale\\ca\\LC\_MESSAGES\\vlc\.mo/
		$s377 = /locale\\ca\@valencia\\LC\_MESSAGES\\vlc\.mo/
		$s378 = /locale\\cgg\\LC\_MESSAGES\\vlc\.mo/
		$s379 = /locale\\co\\LC\_MESSAGES\\vlc\.mo/
		$s380 = /locale\\cs\\LC\_MESSAGES\\vlc\.mo/
		$s381 = /locale\\cy\\LC\_MESSAGES\\vlc\.mo/
		$s382 = /locale\\da\\LC\_MESSAGES\\vlc\.mo/
		$s383 = /locale\\de\\LC\_MESSAGES\\vlc\.mo/
		$s384 = /locale\\el\\LC\_MESSAGES\\vlc\.mo/
		$s385 = /locale\\en\_GB\\LC\_MESSAGES\\vlc\.mo/
		$s386 = /locale\\es\\LC\_MESSAGES\\vlc\.mo/
		$s387 = /locale\\es\_MX\\LC\_MESSAGES\\vlc\.mo/
		$s388 = /locale\\et\\LC\_MESSAGES\\vlc\.mo/
		$s389 = /locale\\eu\\LC\_MESSAGES\\vlc\.mo/
		$s390 = /locale\\fa\\LC\_MESSAGES\\vlc\.mo/
		$s391 = /locale\\ff\\LC\_MESSAGES\\vlc\.mo/
		$s392 = /locale\\fi\\LC\_MESSAGES\\vlc\.mo/
		$s393 = /vlc4/
		$s394 = /\}5vlc/
		$s395 = /  p \= vlc\.playlist\.get\(\)/
		$s396 = /local item \= vlc\.input\.item\(\)/
		$s397 = /    \<\?vlc/
		$s398 = /  \<\?vlc/
		$s399 = /\<vlm\>\<error\>\<\?vlc/
		$s400 = /\?\>No command\<\?vlc/
		$s401 = /vlc\-cache\-gen\.exe\.dbg/
		$s402 = /\*\|\*\|vlc6336/
		$s403 = /\*\|vlc media player\*\|vcl6591/
		$s404 = /\*\|vlc media player\*\|vkc8367/
		$s405 = /\*\|vlc media player\*\|vld8570/
		$s406 = /\*\|vlc media player\*\|vls7178/
		$s407 = /\*\|vlc media player\*\|vlv7112/
		$s408 = /\*\|vlc media player\*\|vlx7027/
		$s409 = /vlc\_dialog\_display\_error/
		$s410 = /vlc\_tls\_ClientCreate/
		$s411 = /vlc\_tls\_ClientSessionCreate/
		$s412 = /vlc\_tls\_Delete/
		$s413 = /vlc\_tls\_GetLine/
		$s414 = /vlc\_tls\_Write/
		$s415 = /vlc\_towc/
		$s416 = /vlc\_uri\_decode/
		$s417 = /libvlc\_InternalCleanup/
		$s418 = /libvlc\_InternalInit/
		$s419 = /vlcsnap\-/
		$s420 = /\%s\\vlcrc/
		$s421 = /\#\#\#  vlc 3\.0\.14/
		$s422 = /vlc\-help\.txt/
		$s423 = /cache vlc 3\.0\.14/
		$s424 = /vlc\_cache\_load/
		$s425 = /vlc\_dialog\_display\_error\_va/
		$s426 = /libvlc\_InternalAddIntf/
		$s427 = /vlc\:\/\/nop/
		$s428 = /\%s\\vlc\-timeshift\.XXXXXX/
		$s429 = /\\tmp\\vlc\-timeshift\.XXXXXX/
		$s430 = /vlc\:/
		$s431 = /vlc\_sd\_Create/
		$s432 = /vlc\_stream\_ReadLine/
		$s433 = /vlc\_stream\_NewMRL/
		$s434 = /vlc\_stream\_NewURL/
		$s435 = /\%s\/icons\/128x128\/vlc\.png/
		$s436 = /vlc\_gl\_surface\_ResizeNotify/
		$s437 = /vlc\_http\_auth\_FormatAuthorizationHeader/
		$s438 = /vlc\_http\_auth\_ParseAuthenticationInfoHeader/
		$s439 = /vlc\_http\_auth\_ParseWwwAuthenticateHeader/
		$s440 = /vlc\_tls\_SocketOpenTLS/
		$s441 = /vlc\_tls\_ServerCreate/
		$s442 = /vlc\_probe/
		$s443 = /vlc\_keystore\_store/
		$s444 = /vlc\_rd\_new/
		$s445 = /vlc\_CPU\_dump/
		$s446 = /vlc\_LogSet/
		$s447 = /vlc\_LogPreinit/
		$s448 = /B\%s\\vlc/
		$s449 = /vlc\_threads\_setup/
		$s450 = /vlc 3\.0\.14/
		$s451 = /http\:\/\/update\.videolan\.org\/vlc\/status\-win\-x64/
		$s452 = /vlcNtk/
		$s453 = /vlck/
		$s454 = /fvlc/
		$s455 = /vlcu/
		$s456 = /ac vlc/
		$s457 = / \"vlc \-I qt\"/
		$s458 = / vlc\:\/\/pause\:\<seconds\> /
		$s459 = / vlc\:\/\/quit /
		$s460 = /u al ficheru vlc\-help\.txt\./
		$s461 = /vlc \-I qt/
		$s462 = / vlc\-help\.txt \./
		$s463 = /VLC\.vlc/
		$s464 = /\.vlc/
		$s465 = /\@videolan\.org\/vlc\,version\=3\.0\.140/
		$s466 = /application\/x\-vlc\-plugin/
		$s467 = / vlc\-help\.txt\./
		$s468 = / \'cvlc\'\, /
		$s469 = /c vlc\./
		$s470 = / \"Ac vlc\" /
		$s471 = /\. \'Cvlc\' /
		$s472 = /vlc\:\/\/ehan\: \<seconds\> Ehana/
		$s473 = /en u vlc\-help\.txt datoteku\./
		$s474 = /em vlc sa zadanim okru/
		$s475 = /vlc \-l qt/
		$s476 = / scrivite \"vlc \-I qt\"/
		$s477 = /vlc h/
		$s478 = / vlc senza interfaccia\./
		$s479 = /n do souboru vlc\-help\.txt/
		$s480 = /kaz \"vlc \-I qt\"/
		$s481 = /kaz \'cvlc\'\./
		$s482 = /vlc\:\/\/quit  Speci/
		$s483 = /hren \"vlc \-I qt\" aus\./
		$s484 = /r \"vlc \-I qt\"/
		$s485 = /\\vlc/
		$s486 = /vlc\_dialog\_display\_progress/
		$s487 = /vlc\_dialog\_release/
		$s488 = /vlc\_fourcc\_GetCodec/
		$s489 = /vlc /
		$s490 = /\. vlc\-/
		$s491 = /t vlc/
		$s492 = /\.\.\/vlcpp\/vlcpp\/common\.hpp/
		$s493 = /14RuntimeNPClassI18LibvlcLogoNPObjectE/
		$s494 = /14RuntimeNPClassI18LibvlcRootNPObjectE/
		$s495 = /14RuntimeNPClassI19LibvlcAudioNPObjectE/
		$s496 = /14RuntimeNPClassI19LibvlcInputNPObjectE/
		$s497 = /14RuntimeNPClassI19LibvlcTitleNPObjectE/
		$s498 = /14RuntimeNPClassI19LibvlcVideoNPObjectE/
		$s499 = /14RuntimeNPClassI21LibvlcChapterNPObjectE/
		$s500 = /14RuntimeNPClassI21LibvlcMarqueeNPObjectE/
		$s501 = /14RuntimeNPClassI22LibvlcPlaylistNPObjectE/
		$s502 = /14RuntimeNPClassI22LibvlcSubtitleNPObjectE/
		$s503 = /14RuntimeNPClassI25LibvlcDeinterlaceNPObjectE/
		$s504 = /14RuntimeNPClassI27LibvlcPlaylistItemsNPObjectE/
		$s505 = /18LibvlcLogoNPObject/
		$s506 = /18LibvlcRootNPObject/
		$s507 = /19LibvlcAudioNPObject/
		$s508 = /19LibvlcInputNPObject/
		$s509 = /19LibvlcTitleNPObject/
		$s510 = /19LibvlcVideoNPObject/
		$s511 = /21LibvlcChapterNPObject/
		$s512 = /21LibvlcMarqueeNPObject/
		$s513 = /22LibvlcPlaylistNPObject/
		$s514 = /22LibvlcSubtitleNPObject/
		$s515 = /25LibvlcDeinterlaceNPObject/
		$s516 = /27LibvlcPlaylistItemsNPObject/
		$s517 = /30LibvlcMediaDescriptionNPObject/
		$s518 = /libvlc\_errmsg/
		$s519 = /libvlc\_media\_list\_player\_event\_manager/
		$s520 = /libvlc\_media\_player\_pause/
		$s521 = /libvlc\_media\_player\_stop/
		$s522 = /libvlc\_video\_set\_callbacks/
		$s523 = /libvlc\_video\_set\_format\_callbacks/
		$s524 = /name\=\"npvlc\.dll\"/
		$s525 = /npvlc\.dll\.dbg/
		$s526 = /vlc\.fullH/
		$s527 = /vlc\.playH/
		$s528 = /vlc\.pausH/
		$s529 = /vlc\.slowH/
		$s530 = /vlc\.muteA/
		$s531 = /vlc\.voluH/
		$s532 = /vlc\.voluI/
		$s533 = /vlc\.miniL/
		$s534 = /vlc\.onToL/
		$s535 = /vlc\.snapL/
		$s536 = /vlc\.toggH/
		$s537 = /vlc\.nextA/
		$s538 = /vlc\.quit/
		$s539 = / \* fix libvlc\_media\_get\_stats/
		$s540 = /vlc\_stream\_Block/
		$s541 = /vlc\_b64\_encode/
		$s542 = /vlc\_getProxyUrl/
		$s543 = /vlc\_memstream\_putc/
		$s544 = /vlc\_uri\_resolve/
		$s545 = /vlc\_b64\_decode/
		$s546 = /vlc\_b64\_decode\_binary\_to\_buffer/
		$s547 = /vlcR/
		$s548 = /FH\~vlc/
		$s549 = /vlc\-ekifananyi/
		$s550 = /vlc\_GetCPUCount/
		$s551 = /vlc\_meta\_AddExtra/
		$s552 = /vlc\_meta\_New/
		$s553 = /rvlc/
		$s554 = /vlcc\= \[csDD/
		$s555 = /libvlc\_add\_intf/
		$s556 = /libvlc\_playlist\_play/
		$s557 = /libvlc\_set\_app\_id/
		$s558 = /libvlc\_set\_user\_agent/
		$s559 = /libvlc\_wait/
		$s560 = /vlc\.exe\.dbg/
		$s561 = /vlc\_init\_avutil/
		$s562 = /s\-\>vlc\_18\.table\_size \=\= 4572/
		$s563 = /error initializing vlc table/
		$s564 = /intra\_vlc/
		$s565 = /rvlc /
		$s566 = /illegal dc vlc/
		$s567 = /cbpy vlc invalid/
		$s568 = /s\-\>alt\_inter\_vlc \=\= 0/
		$s569 = /invalid vlc/
		$s570 = /invalid MV vlc/
		$s571 = /cbp\_vlc\=\%u/
		$s572 = /missing cbpcy\_vlc/
		$s573 = /hgain vlc invalid/
		$s574 = /Exponent vlc invalid/
		$s575 = /vlc length overflow/
		$s576 = /libavcodec\/h264\_cavlc\.c/
		$s577 = /vlc\_fourcc\_GetDescription/
		$s578 = /vlc\_meta\_Set/
		$s579 = /vlc\_stream\_Peek/
		$s580 = /vlc\_stream\_Read/
		$s581 = /vlc\_stream\_Seek/
		$s582 = /vlc\_stream\_Tell/
		$s583 = /vlc\_stream\_vaControl/
		$s584 = /vlc\.nuspecPK/
		$s585 = /tools\/vlc\-3\.0\.14\-win32\_x32\.exePK/
		$s586 = /tools\/vlc\-3\.0\.14\-win64\_x64\.exePK/
		$s587 = /libvlc\_ArtRequest/
		$s588 = /libvlc\_InternalCreate/
		$s589 = /libvlc\_InternalDestroy/
		$s590 = /libvlc\_InternalDialogClean/
		$s591 = /libvlc\_InternalDialogInit/
		$s592 = /libvlc\_InternalKeystoreClean/
		$s593 = /libvlc\_InternalKeystoreInit/
		$s594 = /libvlc\_InternalPlay/
		$s595 = /libvlc\_MetadataCancel/
		$s596 = /libvlc\_MetadataRequest/
		$s597 = /libvlc\_SetExitHandler/
		$s598 = /vlc\_accept/
		$s599 = /vlc\_accept\_i11e/
		$s600 = /vlc\_access\_NewMRL/
		$s601 = /vlc\_actions\_get\_id/
		$s602 = /vlc\_actions\_get\_key\_names/
		$s603 = /vlc\_actions\_get\_keycodes/
		$s604 = /vlc\_b64\_decode\_binary/
		$s605 = /vlc\_b64\_encode\_binary/
		$s606 = /vlc\_cond\_timedwait/
		$s607 = /vlc\_demux\_chained\_ControlVa/
		$s608 = /vlc\_demux\_chained\_Delete/
		$s609 = /vlc\_demux\_chained\_New/
		$s610 = /vlc\_demux\_chained\_Send/
		$s611 = /vlc\_dialog\_display\_progress\_va/
		$s612 = /vlc\_dialog\_id\_dismiss/
		$s613 = /vlc\_dialog\_id\_get\_context/
		$s614 = /vlc\_dialog\_id\_post\_action/
		$s615 = /vlc\_dialog\_id\_post\_login/
		$s616 = /vlc\_dialog\_id\_set\_context/
		$s617 = /vlc\_dialog\_is\_cancelled/
		$s618 = /vlc\_dialog\_provider\_set\_callbacks/
		$s619 = /vlc\_dialog\_provider\_set\_ext\_callback/
		$s620 = /vlc\_dialog\_update\_progress/
		$s621 = /vlc\_dialog\_update\_progress\_text/
		$s622 = /vlc\_dialog\_update\_progress\_text\_va/
		$s623 = /vlc\_dialog\_wait\_login/
		$s624 = /vlc\_dialog\_wait\_login\_va/
		$s625 = /vlc\_dialog\_wait\_question\_va/
		$s626 = /vlc\_drand48/
		$s627 = /vlc\_epg\_AddEvent/
		$s628 = /vlc\_epg\_Delete/
		$s629 = /vlc\_epg\_Duplicate/
		$s630 = /vlc\_epg\_New/
		$s631 = /vlc\_epg\_SetCurrent/
		$s632 = /vlc\_epg\_event\_Delete/
		$s633 = /vlc\_epg\_event\_Duplicate/
		$s634 = /vlc\_epg\_event\_New/
		$s635 = /vlc\_error/
		$s636 = /vlc\_event\_attach/
		$s637 = /vlc\_event\_detach/
		$s638 = /vlc\_ext\_dialog\_update/
		$s639 = /vlc\_fifo\_DequeueAllUnlocked/
		$s640 = /vlc\_fifo\_GetBytes/
		$s641 = /vlc\_fifo\_QueueUnlocked/
		$s642 = /vlc\_fifo\_WaitCond/
		$s643 = /vlc\_filenamecmp/
		$s644 = /vlc\_getaddrinfo\_i11e/
		$s645 = /vlc\_getcwd/
		$s646 = /vlc\_html\_color/
		$s647 = /vlc\_http\_auth\_Deinit/
		$s648 = /vlc\_http\_auth\_Init/
		$s649 = /vlc\_http\_cookies\_destroy/
		$s650 = /vlc\_http\_cookies\_fetch/
		$s651 = /vlc\_http\_cookies\_new/
		$s652 = /vlc\_http\_cookies\_store/
		$s653 = /vlc\_iconv/
		$s654 = /vlc\_iconv\_close/
		$s655 = /vlc\_iconv\_open/
		$s656 = /vlc\_interrupt\_create/
		$s657 = /vlc\_interrupt\_destroy/
		$s658 = /vlc\_interrupt\_forward\_start/
		$s659 = /vlc\_interrupt\_forward\_stop/
		$s660 = /vlc\_interrupt\_kill/
		$s661 = /vlc\_interrupt\_raise/
		$s662 = /vlc\_interrupt\_set/
		$s663 = /vlc\_keycode2str/
		$s664 = /vlc\_keystore\_create/
		$s665 = /vlc\_keystore\_find/
		$s666 = /vlc\_keystore\_release/
		$s667 = /vlc\_keystore\_remove/
		$s668 = /vlc\_list\_children/
		$s669 = /vlc\_list\_release/
		$s670 = /vlc\_loaddir/
		$s671 = /vlc\_lrand48/
		$s672 = /vlc\_lstat/
		$s673 = /vlc\_memfd/
		$s674 = /vlc\_memstream\_flush/
		$s675 = /vlc\_memstream\_vprintf/
		$s676 = /vlc\_meta\_CopyExtraNames/
		$s677 = /vlc\_meta\_Delete/
		$s678 = /vlc\_meta\_Get/
		$s679 = /vlc\_meta\_GetExtra/
		$s680 = /vlc\_meta\_GetExtraCount/
		$s681 = /vlc\_meta\_GetStatus/
		$s682 = /vlc\_meta\_Merge/
		$s683 = /vlc\_meta\_SetStatus/
		$s684 = /vlc\_meta\_TypeToLocalizedString/
		$s685 = /vlc\_mime\_Ext2Mime/
		$s686 = /vlc\_mkdir/
		$s687 = /vlc\_mkstemp/
		$s688 = /vlc\_mutex\_init\_recursive/
		$s689 = /vlc\_mutex\_trylock/
		$s690 = /vlc\_ngettext/
		$s691 = /vlc\_object\_find\_name/
		$s692 = /vlc\_object\_get\_name/
		$s693 = /vlc\_object\_hold/
		$s694 = /vlc\_pipe/
		$s695 = /vlc\_rd\_get\_names/
		$s696 = /vlc\_rd\_probe\_add/
		$s697 = /vlc\_rd\_release/
		$s698 = /vlc\_readv\_i11e/
		$s699 = /vlc\_recvmsg\_i11e/
		$s700 = /vlc\_renderer\_item\_demux\_filter/
		$s701 = /vlc\_renderer\_item\_flags/
		$s702 = /vlc\_renderer\_item\_hold/
		$s703 = /vlc\_renderer\_item\_icon\_uri/
		$s704 = /vlc\_renderer\_item\_name/
		$s705 = /vlc\_renderer\_item\_new/
		$s706 = /vlc\_renderer\_item\_release/
		$s707 = /vlc\_renderer\_item\_sout/
		$s708 = /vlc\_renderer\_item\_type/
		$s709 = /vlc\_rtsp\_HostNew/
		$s710 = /vlc\_rwlock\_destroy/
		$s711 = /vlc\_rwlock\_init/
		$s712 = /vlc\_rwlock\_rdlock/
		$s713 = /vlc\_rwlock\_unlock/
		$s714 = /vlc\_rwlock\_wrlock/
		$s715 = /vlc\_scandir/
		$s716 = /vlc\_sd\_Destroy/
		$s717 = /vlc\_sd\_GetNames/
		$s718 = /vlc\_sd\_probe\_Add/
		$s719 = /vlc\_sdp\_Start/
		$s720 = /vlc\_sem\_wait\_i11e/
		$s721 = /vlc\_sendmsg\_i11e/
		$s722 = /vlc\_sendto\_i11e/
		$s723 = /vlc\_socket/
		$s724 = /vlc\_socketpair/
		$s725 = /vlc\_str2keycode/
		$s726 = /vlc\_strcasestr/
		$s727 = /vlc\_stream\_CommonNew/
		$s728 = /vlc\_stream\_Delete/
		$s729 = /vlc\_stream\_Eof/
		$s730 = /vlc\_stream\_FilterDefaultReadDir/
		$s731 = /vlc\_stream\_FilterNew/
		$s732 = /vlc\_stream\_MemoryNew/
		$s733 = /vlc\_stream\_ReadBlock/
		$s734 = /vlc\_stream\_ReadDir/
		$s735 = /vlc\_stream\_ReadPartial/
		$s736 = /vlc\_stream\_directory\_Attach/
		$s737 = /vlc\_stream\_extractor\_Attach/
		$s738 = /vlc\_stream\_extractor\_CreateMRL/
		$s739 = /vlc\_stream\_fifo\_Close/
		$s740 = /vlc\_stream\_fifo\_New/
		$s741 = /vlc\_stream\_fifo\_Queue/
		$s742 = /vlc\_stream\_fifo\_Write/
		$s743 = /vlc\_strerror/
		$s744 = /vlc\_strfinput/
		$s745 = /vlc\_thread\_id/
		$s746 = /vlc\_thread\_self/
		$s747 = /vlc\_threadvar\_create/
		$s748 = /vlc\_threadvar\_delete/
		$s749 = /vlc\_threadvar\_get/
		$s750 = /vlc\_threadvar\_set/
		$s751 = /vlc\_timer\_getoverrun/
		$s752 = /vlc\_tls\_ServerSessionCreate/
		$s753 = /vlc\_tls\_SocketOpen/
		$s754 = /vlc\_tls\_SocketOpenAddrInfo/
		$s755 = /vlc\_tls\_SocketPair/
		$s756 = /vlc\_uri2path/
		$s757 = /vlc\_uri\_fixup/
		$s758 = /vlc\_vaLog/
		$s759 = /vlc\_write\_i11e/
		$s760 = /vlc\_writev/
		$s761 = /vlc\_writev\_i11e/
		$s762 = /vlc\_xml\_decode/
		$s763 = /vlc\_xml\_encode/
		$s764 = /libvlccore\.dll\.dbg/
		$s765 = /vlc\_poll\_i11e interrupted/
		$s766 = /vlc\_poll\_i11e failed/
		$s767 = /vlc\_rpc\_mainloop/
		$s768 = /\,  \"ac vlc\" /
		$s769 = /User\-Agent\: vlc\/3\.0\.14/
		$s770 = /vlc\{/
		$s771 = /axvlc\.dll\.dbg/
		$s772 = /\<vlc\:item tid\=\"\%i\"\/\>/
		$s773 = /\<vlc\:node title\=\"\%s\"\>/
		$s774 = /\<\/vlc\:node\>/
		$s775 = /\<vlc\:id\>\%i\<\/vlc\:id\>/
		$s776 = /\<vlc\:option\>\%s\<\/vlc\:option\>/
		$s777 = /Avlc/
		$s778 = /3\;vlc/
		$s779 = /Kvlc/
		$s780 = /vlc\_Loeb5130/
		$s781 = /vlc\)/
		$s782 = /vlc 3\.0\.M/
		$s783 = /vlc\+\&r\:B/
		$s784 = /M\_vlc/
		$s785 = /vlc\@videolan\.org/
		$s786 = /6vlc/
		$s787 = /SLIQ\_I\:\:MbCoder\:\:cavlcEncodeHeader\_ENC/
		$s788 = /SLIQ\_I\:\:MbCoder\:\:cavlcEncodeHeader\_RATE/
		$s789 = /SLIQ\_I\:\:H264SliceDecoder\:\:CavlcResidualBlock/
		$s790 = /SLIQ\_I\:\:H264SliceDecoder\:\:CavlcResidual/
		$s791 = /SLIQ\_I\:\:H264SliceDecoder\:\:CavlcIPred/
		$s792 = /SLIQ\_I\:\:H264SliceDecoder\:\:CavlcMbPred/
		$s793 = /SLIQ\_I\:\:H264SliceDecoder\:\:CavlcSubMbPred/
		$s794 = /SLIQ\_I\:\:H264SliceDecoder\:\:CavlcDecodeMb/
		$s795 = /vlcjo/
		$s796 = /vlc\!Fag/
		$s797 = /8ovlcK/
		$s798 = /vlcs/
		$s799 = /\-vlc/
		$s800 = /vlc 3\.0\.14 stream output/
		$s801 = /  \"ac vlc\" /
		$s802 = /iteks\, et parandada \"ac vlc\"/
		$s803 = /lju vlc\-st/
		$s804 = /vlc\_sd\_probe\_Open/
		$s805 = /vlc\_rd\_probe\_open/
		$s806 = /vlc\-errors/
		$s807 = /1cancel\(vlc\_dialog\_id \*\)/
		$s808 = /2cancelled\(vlc\_dialog\_id \*\)/
		$s809 = /vlc\-progress/
		$s810 = /vlc\-login/
		$s811 = /vlc\-plugins/
		$s812 = /\:\/logo\/vlc48\.png/
		$s813 = /vlc\-stream\-output/
		$s814 = /vlc\-convert/
		$s815 = /vlc\-help/
		$s816 = /vlc\-update/
		$s817 = /\:\/logo\/vlc256\.png/
		$s818 = /vlc\-about/
		$s819 = /vlc\-goto\-time/
		$s820 = /vlc\/button\-bar/
		$s821 = /\:\/logo\/vlc128\.png/
		$s822 = /vlc\-toolbars\-editor/
		$s823 = /vlc\-open\-media/
		$s824 = /vlc\-open\-url/
		$s825 = /vlc\-privacy/
		$s826 = / vlc \-I qt /
		$s827 = /\/home\/jenkins\/workspace\/vlc\-release\/w/
		$s828 = /n vlc oletusk/
		$s829 = / vlc\:t/
		$s830 = /vlc\-ruutukaappaus/
		$s831 = / tal file vlc\-help\.txt/
		$s832 = / vlc cence interface\./
		$s833 = /ld opslein nei vlc\-help\.txt\./
		$s834 = /k \'cvlc\' foar VLC s/
		$s835 = /rva a vlc\-help\.txt f/
		$s836 = /  vlc\:\/\/pause\:\<m/
		$s837 = /vlc\-k/
		$s838 = /s a vlc\-b/
		$s839 = / vlc\-help\.txt file\./
		$s840 = /u \"vlc \-I qt\"/
		$s841 = /Keyri vlc me/
		$s842 = /u \'cvlc\' til a/
		$s843 = / keyra vlc /
		$s844 = /vlc\-grip/
		$s845 = /r vlc/
		$s846 = /\"vlc \-I qt\"/
		$s847 = /\'cvlc\'/
		$s848 = /\"ac vlc\"/
		$s849 = /Rularea vlc f/
		$s850 = /  vlc\:\/\/pause\:\</
		$s851 = /boru vlc\-help\.txt\./
		$s852 = /llet till filen vlc\-help\.txt\./
		$s853 = /r vlc l/
		$s854 = /r vlc med standardgr/
		$s855 = /nd \"cvlc\" f/
		$s856 = /nda vlc utan gr/
		$s857 = / \'cvlc\'/
		$s858 = /erik vlc\-help\.txt dosyas/
		$s859 = /vlc yaz/
		$s860 = /in \'cvlc\' kullan/
		$s861 = /i\: vlc\-help\.txt file\./
		$s862 = /nh \"vlc \-l qt\"/
		$s863 = /c vlc /
		$s864 = /ng \'cvlc\' /
		$s865 = /a \"ac vlc\" v/
		$s866 = /nh vlc/
		$s867 = /Enondaedje vlc avou l\' pr/
		$s868 = / \'cvlc\' po eploy/
		$s869 = / vlc sins eterface\./
		$s870 = /vlc\-assaetchaedje/
		$s871 = /ukuthwebula kwe\-vlc/
		$s872 = /icale\\fr\\LC\_MESSAGES\\vlc\.mo/
		$s873 = /locale\\fur\\LC\_MESSAGES\\vlc\.mo/
		$s874 = /locale\\fy\\LC\_MESSAGES\\vlc\.mo/
		$s875 = /locale\\ga\\LC\_MESSAGES\\vlc\.mo/
		$s876 = /locale\\gd\\LC\_MESSAGES\\vlc\.mo/
		$s877 = /locale\\gl\\LC\_MESSAGES\\vlc\.mo/
		$s878 = /locale\\gu\\LC\_MESSAGES\\vlc\.mo/
		$s879 = /locale\\he\\LC\_MESSAGES\\vlc\.mo/
		$s880 = /locale\\hi\\LC\_MESSAGES\\vlc\.mo/
		$s881 = /locale\\hr\\LC\_MESSAGES\\vlc\.mo/
		$s882 = /locale\\hu\\LC\_MESSAGES\\vlc\.mo/
		$s883 = /locale\\hy\\LC\_MESSAGES\\vlc\.mo/
		$s884 = /locale\\id\\LC\_MESSAGES\\vlc\.mo/
		$s885 = /locale\\is\\LC\_MESSAGES\\vlc\.mo/
		$s886 = /locale\\it\\LC\_MESSAGES\\vlc\.mo/
		$s887 = /locale\\ja\\LC\_MESSAGES\\vlc\.mo/
		$s888 = /locale\\ka\\LC\_MESSAGES\\vlc\.mo/
		$s889 = /locale\\kab\\LC\_MESSAGES\\vlc\.mo/
		$s890 = /locale\\kk\\LC\_MESSAGES\\vlc\.mo/
		$s891 = /locale\\km\\LC\_MESSAGES\\vlc\.mo/
		$s892 = /locale\\kn\\LC\_MESSAGES\\vlc\.mo/
		$s893 = /locale\\ko\\LC\_MESSAGES\\vlc\.mo/
		$s894 = /locale\\ks\_IN\\LC\_MESSAGES\\vlc\.mo/
		$s895 = /locale\\ku\_IQ\\LC\_MESSAGES\\vlc\.mo/
		$s896 = /locale\\ky\\LC\_MESSAGES\\vlc\.mo/
		$s897 = /locale\\lg\\LC\_MESSAGES\\vlc\.mo/
		$s898 = /locale\\lt\\LC\_MESSAGES\\vlc\.mo/
		$s899 = /locale\\lv\\LC\_MESSAGES\\vlc\.mo/
		$s900 = /locale\\mai\\LC\_MESSAGES\\vlc\.mo/
		$s901 = /locale\\ml\\LC\_MESSAGES\\vlc\.mo/
		$s902 = /locale\\mn\\LC\_MESSAGES\\vlc\.mo/
		$s903 = /locale\\mr\\LC\_MESSAGES\\vlc\.mo/
		$s904 = /locale\\ms\\LC\_MESSAGES\\vlc\.mo/
		$s905 = /locale\\nb\\LC\_MESSAGES\\vlc\.mo/
		$s906 = /locale\\ne\\LC\_MESSAGES\\vlc\.mo/
		$s907 = /locale\\nl\\LC\_MESSAGES\\vlc\.mo/
		$s908 = /locale\\nn\\LC\_MESSAGES\\vlc\.mo/
		$s909 = /locale\\oc\\LC\_MESSAGES\\vlc\.mo/
		$s910 = /locale\\pa\\LC\_MESSAGES\\vlc\.mo/
		$s911 = /locale\\pl\\LC\_MESSAGES\\vlc\.mo/
		$s912 = /locale\\ps\\LC\_MESSAGES\\vlc\.mo/
		$s913 = /locale\\pt\_BR\\LC\_MESSAGES\\vlc\.mo/
		$s914 = /locale\\pt\_PT\\LC\_MESSAGES\\vlc\.mo/
		$s915 = /locale\\ro\\LC\_MESSAGES\\vlc\.mo/
		$s916 = /locale\\ru\\LC\_MESSAGES\\vlc\.mo/
		$s917 = /locale\\si\\LC\_MESSAGES\\vlc\.mo/
		$s918 = /locale\\sk\\LC\_MESSAGES\\vlc\.mo/
		$s919 = /locale\\sl\\LC\_MESSAGES\\vlc\.mo/
		$s920 = /locale\\sq\\LC\_MESSAGES\\vlc\.mo/
		$s921 = /locale\\sr\\LC\_MESSAGES\\vlc\.mo/
		$s922 = /locale\\sv\\LC\_MESSAGES\\vlc\.mo/
		$s923 = /locale\\ta\\LC\_MESSAGES\\vlc\.mo/
		$s924 = /locale\\te\\LC\_MESSAGES\\vlc\.mo/
		$s925 = /locale\\th\\LC\_MESSAGES\\vlc\.mo/
		$s926 = /locale\\tr\\LC\_MESSAGES\\vlc\.mo/
		$s927 = /locale\\tt\\LC\_MESSAGES\\vlc\.mo/
		$s928 = /locale\\ug\\LC\_MESSAGES\\vlc\.mo/
		$s929 = /locale\\uk\\LC\_MESSAGES\\vlc\.mo/
		$s930 = /locale\\uz\\LC\_MESSAGES\\vlc\.mo/
		$s931 = /locale\\vi\\LC\_MESSAGES\\vlc\.mo/
		$s932 = /locale\\wa\\LC\_MESSAGES\\vlc\.mo/
		$s933 = /locale\\zh\_CN\\LC\_MESSAGES\\vlc\.mo/
		$s934 = /locale\\zh\_TW\\LC\_MESSAGES\\vlc\.mo/
		$s935 = /locale\\zu\\LC\_MESSAGES\\vlc\.mo/
		$s936 = /lua\\http\\images\\vlc\-48\.png/
		$s937 = /lua\\http\\images\\vlc16x16\.png/
		$s938 = /call\_libvlc\_command/
		$s939 = /vlc\_err/
		$s940 = /libvlc\_command/
		$s941 = /vlcerr/
		$s942 = /my\_vlc\_load/
		$s943 = /vlc\-qt\-interface/
		$s944 = /vlc\-xmas/
		$s945 = /\:\/logo\/vlc128\-xmas\.png/
		$s946 = /\:\/logo\/vlc16\.png/
		$s947 = /vlc\-main/
		$s948 = /vlc\-playlist/
		$s949 = /vlc\-bookmarks/
		$s950 = /vlc\-preferences/
		$s951 = /vlc\-media\-info/
		$s952 = /vlc\-extended/
		$s953 = /vlc\-messages/
		$s954 = /vlc\-key\-input/
		$s955 = /vlc\-advanced\-options/
		$s956 = /\:\/logo\/vlc128\-kb\.png/
		$s957 = /vlc\/qt\-input\-items/
		$s958 = /vlc\_renderer\_item\_t\*/
		$s959 = /vlc\_dialog\_id\*/
		$s960 = /vlc\-3\.0\.14\-win64\_x64\.exe/
		$s961 = /nstalleerd hebt \"vlc \-l qt\"\./
		$s962 = /Aviada de vlc amb l\'interf/
		$s963 = /Uruchamianie vlc z domy/
		$s964 = /yj \'cvlc\'\, aby u/
		$s965 = / vlc bez interfejsu\./
		$s966 = /ierul vlc\-help\.txt\./
		$s967 = /vlc\/3\.0\.14/
		$s968 = /vlc\_http\_dbg/
		$s969 = /vlc\_http\_err/
		$s970 = /  vlc\:\/\/pause\:\<sekund/
		$s971 = /vlc\-nuotrauka/
		$s972 = / \'cvlc\'\-/
		$s973 = /\!vlc/
		$s974 = /1gvlc\{/
		$s975 = /p\+vlc\:/
		$s976 = /\?vlc\!/
		$s977 = /vlc\=g\~W/
		$s978 = /yvlc/
		$s979 = /\}\,\?vlcI/
		$s980 = /CZvlc/
		$s981 = /2Xvlc/
		$s982 = /vlc\=/
		$s983 = /\#vlc/
		$s984 = /vlcn\=\_/
		$s985 = /fvlc/
		$s986 = /bvlc44/
		$s987 = /vlc2/
		$s988 = /FJvlc/
		$s989 = /vlcd\_/
		$s990 = /vlcE/
		$s991 = /Wvlc/
		$s992 = /0vlc/
		$s993 = /\\Fvlc/
		$s994 = /vlc\.isPlI/
		$s995 = /vlc\.isStI/
		$s996 = /vlc\.isPaI/
		$s997 = /vlc\.isSeA/
		$s998 = /vlc\.canRI/
		$s999 = /vlc\.isRe/
		$s1000 = /vlc\.isFuH/
		$s1001 = /vlc\.hasVH/
		$s1002 = /vlc\.hasAI/
		$s1003 = /vlc\.isMuM/
		$s1004 = /vlc\.isOnL/
		$s1005 = /vlc\.stop\(\)/
		$s1006 = /vlc\.faster\(\)/
		$s1007 = /vlc\:\/\/dummy/
		$s1008 = /vlclua\_extension\_require/
		$s1009 = /vlclua\_extension\_dialog\_callback/
		$s1010 = /vlclua\_sd\_description/
		$s1011 = /vlclua\_probe\_sd/
		$s1012 = /vlclua\_read\_input\_item/
		$s1013 = /vlclua\_read\_options/
		$s1014 = /vlclua\_read\_custom\_meta\_data/
		$s1015 = /vlclua\_read\_meta\_data/
		$s1016 = /vlclua\_scripts\_batch\_execute/
		$s1017 = /vlclua\_config\_get/
		$s1018 = /vlclua\_config\_set/
		$s1019 = /vlc\.dialog\(\) usage\: \(title\)/
		$s1020 = /vlclua\_dialog\_delete/
		$s1021 = /vlclua\_dialog\_create/
		$s1022 = /vlclua\_httpd\_handler\_callback/
		$s1023 = /vlclua\_httpd\_file\_callback/
		$s1024 = /vlclua\_msg\_dbg/
		$s1025 = /vlclua\_msg\_warn/
		$s1026 = /vlclua\_msg\_err/
		$s1027 = /vlclua\_msg\_info/
		$s1028 = /vlc\_object/
		$s1029 = /vlclua\_playlist\_add\_common/
		$s1030 = /vlclua\_item\_set\_title/
		$s1031 = /vlclua\_item\_set\_artist/
		$s1032 = /vlclua\_item\_set\_genre/
		$s1033 = /vlclua\_item\_set\_copyright/
		$s1034 = /vlclua\_item\_set\_album/
		$s1035 = /vlclua\_item\_set\_tracknum/
		$s1036 = /vlclua\_item\_set\_description/
		$s1037 = /vlclua\_item\_set\_rating/
		$s1038 = /vlclua\_item\_set\_date/
		$s1039 = /vlclua\_item\_set\_setting/
		$s1040 = /vlclua\_item\_set\_url/
		$s1041 = /vlclua\_item\_set\_language/
		$s1042 = /vlclua\_item\_set\_nowplaying/
		$s1043 = /vlclua\_item\_set\_publisher/
		$s1044 = /vlclua\_item\_set\_encodedby/
		$s1045 = /vlclua\_item\_set\_arturl/
		$s1046 = /vlclua\_item\_set\_trackid/
		$s1047 = /vlclua\_item\_set\_tracktotal/
		$s1048 = /vlclua\_item\_set\_director/
		$s1049 = /vlclua\_item\_set\_season/
		$s1050 = /vlclua\_item\_set\_episode/
		$s1051 = /vlclua\_item\_set\_showname/
		$s1052 = /vlclua\_item\_set\_actors/
		$s1053 = /vlclua\_sd\_create\_item/
		$s1054 = /vlclua\_sd\_create\_node/
		$s1055 = /vlclua\_stream\_read/
		$s1056 = /vlclua\_stream\_add\_filter/
		$s1057 = /vlclua\_stream\_readdir/
		$s1058 = /vlclua\_directory\_stream\_new/
		$s1059 = /vlclua\_from\_charset/
		$s1060 = /vlclua\_pushvalue/
		$s1061 = /vlclua\_tovalue/
		$s1062 = /vlclua\_var\_toggle\_or\_set/
		$s1063 = /vlclua\_fullscreen/
		$s1064 = /Usage\: vlc\.io\.unlink\(path\)/
		$s1065 = /Usage\: vlc\.io\.readdir\(name\)/
		$s1066 = /vlclua\_mkdir/
		$s1067 = /Pvlcz/
		$s1068 = /dj1vlc/
		$s1069 = /8dvlc38/
		$s1070 = /\<vlc/
		$s1071 = /vlcO/
		$s1072 = /Jvlc/
		$s1073 = /\{\\\*\\pn\\pnlvlcont\\ppnucrmLIGHTGOLDENRODYELLOW/
		$s1074 = /vlcSc/
		$s1075 = / vlc\-help\.txt/
		$s1076 = /22vlc\_stream\_io\_callback/
		$s1077 = /xmlns\:vlc/
		$s1078 = /vlc\:node/
		$s1079 = /vlc\:id/
		$s1080 = /vlc\:item/
		$s1081 = /vlc\:option/
		$s1082 = /http\:\/\/www\.videolan\.org\/vlc\/playlist\/0/
		$s1083 = /parse\_vlcnode\_node/
		$s1084 = /\. \'cvlc\' /
		$s1085 = /\_G\.vlm \= vlc\.vlm\(\)/
		$s1086 = /URL\=https\:\/\/www\.videolan\.org\/\/vlc\/skins\.php/
		$s1087 = /\+vlc/
		$s1088 = /vlcx5\;T\=P/
		$s1089 = /\{\\a\?2iwvlc\^/
		$s1090 = /vlc/
		$s1091 = /itvlc/
		$s1092 = /\$vlcu/
		$s1093 = /vlc\`/
		$s1094 = /vlc\[d/
		$s1095 = /vlc\$/
		$s1096 = /h\?vlc/
	condition:
		876 of ($s*)
}