rule WinRAR_install {
	meta:
		description = "Auto gene for WinRAR"
		author = "David Cruciani"
		date = "2021-06-14"
		versionApp = "6.1.0"
		uuid = "3d458185-f612-46a1-b204-6229679021f1"
	strings: 
		$s0 = /winrar\.exe\|55dc552369664f2a/
		$s1 = /\*\|\*\|winrar7231/
		$s2 = /Roshal\.WinRAR\.WinRAR/
		$s3 = /WinRARra/
		$s4 = /WinRAR SFXctures/
		$s5 = /C\%\%Program Files\%WinRAR/
		$s6 = /es accidentelles par WinRAR\./
		$s7 = /tre facultatif\, WinRAR d/
		$s8 = /ant WinRAR /
		$s9 = /faut WinRAR cr/
		$s10 = /ches\. WinRAR/
		$s11 = /\, WinRAR essayera de d/
		$s12 = /rs par WinRAR sont /
		$s13 = /le\. Si WinRAR d/
		$s14 = /winrar\.exe/
		$s15 = /  name\=\"WinRAR SFX\"/
		$s16 = /  name\=\"WinRAR\"/
		$s17 = /WinRAR\.chm/
		$s18 = /WinRAR\.exe/
		$s19 = /winrar\.lng/
		$s20 = /winrar\.chw/
		$s21 = /winrar\~/
		$s22 = /faut\, WinRAR r/
		$s23 = / WinRAR /
		$s24 = /es \"Archive WinRAR\" et /
		$s25 = /ration WinRAR et les bo/
		$s26 = /tre de WinRAR comme dans/
		$s27 = /grer WinRAR /
		$s28 = /es\, WinRAR/
		$s29 = /tat de WinRAR\./
		$s30 = /demment\, WinRAR n\'/
		$s31 = / des utilisateurs de WinRAR\./
		$s32 = /e\, WinRAR affichait un num/
		$s33 = /tres de WinRAR incluait/
		$s34 = /nes WinRAR pr/
		$s35 = /me d\'interface WinRAR /
		$s36 = / WinRAR\.exe et est ignor/
		$s37 = /tres WinRAR et s/
		$s38 = /dentes de WinRAR\. Les donn/
		$s39 = /taient illisibles\. WinRAR /
		$s40 = /tres de WinRAR\,/
		$s41 = / de WinRAR/
		$s42 = /es\, WinRAR v/
		$s43 = /es dans Unix\, WinRAR associe/
		$s44 = /  15\. WinRAR emp/
		$s45 = /s\, WinRAR tente de d/
		$s46 = /tres de WinRAR\. Vous pr/
		$s47 = / Fichier WinRAR\.ini /
		$s48 = / de l\'aide WinRAR\./
		$s49 = /te de dialogue WinRAR /
		$s50 = / de WinRAR gr/
		$s51 = /dentes de WinRAR\./
		$s52 = /mentaire ZIP\. WinRAR peut d/
		$s53 = /s par WinRAR comme /
		$s54 = / par WinRAR\./
		$s55 = /faut\, WinRAR continuait /
		$s56 = /tres de WinRAR\./
		$s57 = / contextuel de WinRAR \;/
		$s58 = /compression\. WinRAR cr/
		$s59 = /dentes de WinRAR\,/
		$s60 = /diteur externe\, WinRAR /
		$s61 = /dentes de WinRAR /
		$s62 = /e\, WinRAR /
		$s63 = / d\'installer WinRAR version/
		$s64 = /tre principale de WinRAR/
		$s65 = / WinRAR\!\<\/h5\>/
		$s66 = / winrar/
		$s67 = /winrar/
		$s68 = / winrarOAide de/
		$s69 = / WinRARB\*\|/
		$s70 = /O\|winrar/
		$s71 = /\|WinRARB\*\|/
		$s72 = /u rapide de WinRAR/
		$s73 = /\/html\/HELPWinRARIni\.htm/
		$s74 = /\/winrar\.hhc/
		$s75 = /\/winrar\.hhk/
		$s76 = /WinRAR/
		$s77 = /j  WinRAR\.exe/
		$s78 = /R\/D  winrar\.chm/
		$s79 = /de winrar\~/
		$s80 = /aide de winrar\~/
		$s81 = /winrar v6\.01 \[Approved\]/
		$s82 = /winrar v6\.01/
		$s83 = /\*\|\*\|winrar7729/
		$s84 = /\*\|winrar\*\|winz7238/
		$s85 = /\*\|winrar\*\|winwar7230/
		$s86 = /\*\|winrar\*\|win rar5709/
		$s87 = /WinRAR7/
		$s88 = /WinRAR4\~/
		$s89 = /WinRAR\.ZIP/
		$s90 = /WinRAR32/
		$s91 = /WinRARab/
		$s92 = /WinRARtV/
		$s93 = /WinRARtt/
		$s94 = /WinRARI\]/
		$s95 = /WinRAR\.REV\|/
		$s96 = /WinRAR archiver/
		$s97 = /\$packageSearch \= \"WinRAR\*\"/
		$s98 = /WinRAR\.lnk/
		$s99 = / WinRAR/
		$s100 = /q  WinRAR\.lnk/
	condition:
		80 of ($s*)
}